import { CRIT, type LessonSeed, type PhaseSeed } from './content-types.js';

// Helper para crear lecciones de UI real con su reto en la Fase 3.
function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  estimatedTimeMinutes: number,
  challenge: LessonSeed['challenge'],
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes, challenge };
}

export const phase03: PhaseSeed = {
  code: 'FASE 3',
  title: 'UI Design real',
  objective: 'Aprender patrones reales de interfaz.',
  unlockedSkills: ['mobile-ui', 'web-ui', 'forms'],
  projects: [
    'Pantalla de login',
    'Onboarding móvil',
    'Formulario de registro',
    'Página de ajustes',
    'Checkout básico',
    'Mini app móvil de 5 pantallas',
  ],
  lessons: [
    lesson(
      'La pantalla de login: simple o rota',
      'Diseñar una pantalla de login clara, usable y con gestión de estados.',
      'El login es la primera pantalla real que verá el usuario. Si genera fricción, abandona. El diseño debe ser mínimo: email, contraseña, botón. Sin adornos que distraigan del objetivo.\n\nCada campo tiene al menos cuatro estados: default, focus, error y disabled. Diseñar solo el estado default es diseñar a medias. El estado de error necesita un mensaje claro, no solo un borde rojo.\n\nEl CTA de acceso debe ser el elemento más prominente. Los enlaces secundarios (¿olvidaste la contraseña? / Crear cuenta) existen, pero sin competir en peso visual con el botón principal.',
      ['Estados de input (default, focus, error, disabled)', 'Jerarquía de acciones', 'Feedback de errores', 'CTA único'],
      ['Auto Layout', 'Componentes', 'Estilos de color', 'Estilos de texto'],
      40,
      {
        title: 'Pantalla de login',
        brief: 'Diseña la pantalla de login de una app de gestión de proyectos para equipos. Debe funcionar en móvil (375px). Incluye los estados default, error en contraseña y loading del botón.',
        context: 'Es la puerta de entrada del producto. Un mal login genera desconfianza desde el minuto cero.',
        objective: 'Crear un login limpio con estados bien definidos y jerarquía clara.',
        targetUser: 'Profesional que accede a su herramienta de trabajo desde el móvil.',
        restrictions: [
          'Frame de 375px de ancho.',
          'Incluir mínimo 3 estados: default, error en contraseña y botón en loading.',
          'Un solo CTA primario.',
          'Sin imágenes decorativas que ocupen más del 20% del espacio.',
          'Auto Layout en todos los grupos de elementos.',
        ],
        deliverables: [
          '3 frames: estado default, error y loading.',
          'Mensaje de error visible y claro (no solo borde rojo).',
          'Link de Figma + captura.',
        ],
        checklist: [
          'El CTA es el elemento de mayor peso visual.',
          'El error explica qué falló, no solo lo marca.',
          'Los estados de input son visualmente distintos.',
          'El espaciado es consistente entre campos.',
          'El botón tiene estado loading reconocible.',
        ],
        commonMistakes: [
          'Diseñar solo el estado default.',
          'Mensaje de error genérico ("Error") sin contexto.',
          'Dos CTAs del mismo peso visual.',
          'Input de contraseña sin toggle de visibilidad.',
          'Texto de los campos demasiado pequeño para móvil (menos de 16px).',
        ],
        difficulty: 2,
        timeLimitMinutes: 50,
        skills: ['mobile-ui', 'forms', 'components'],
        rubric: [
          CRIT.jerarquia(true),
          CRIT.espaciado(),
          CRIT.consistencia(),
          CRIT.ux(true),
          CRIT.tipografia(),
          CRIT.autolayout(),
        ],
      },
    ),
    lesson(
      'Onboarding móvil: convencer sin aburrir',
      'Diseñar un flujo de onboarding de 3 pasos que enganche sin agotar al usuario.',
      'El onboarding tiene una sola misión: que el usuario llegue al valor del producto lo antes posible. Cada pantalla extra es fricción. Tres pasos, máximo cuatro. Sin párrafos de texto que nadie lee.\n\nCada paso de onboarding tiene la misma estructura: ilustración o icono grande, titular corto, subtítulo de una línea, indicador de progreso y botón siguiente. La consistencia entre pantallas es lo que da sensación de producto cuidado.\n\nLos indicadores de progreso (dots) son obligatorios. El usuario necesita saber cuánto queda. El último paso tiene un CTA diferente al resto: no "Siguiente" sino "Empezar" o "Listo".',
      ['Flujo de pantallas', 'Onboarding de 3 pasos', 'Indicador de progreso', 'Consistencia entre pantallas', 'CTA final'],
      ['Auto Layout', 'Componentes', 'Prototyping básico', 'Frames móvil'],
      45,
      {
        title: 'Onboarding móvil',
        brief: 'Diseña el onboarding de 3 pasos de una app de hábitos saludables. El usuario debe entender qué hace la app y sentirse motivado antes de crear su cuenta.',
        context: 'El onboarding es la primera impresión. Si es aburrido o largo, el usuario cierra la app.',
        objective: 'Flujo de 3 pantallas consistentes que transmiten valor de forma directa.',
        targetUser: 'Adulto de 25-40 años que acaba de descargar la app por primera vez.',
        restrictions: [
          'Exactamente 3 pantallas de onboarding.',
          'Frame de 375px de ancho.',
          'Máximo 2 líneas de subtítulo por pantalla.',
          'Indicador de progreso (dots) visible en las 3 pantallas.',
          'El texto del CTA del último paso debe ser diferente al de los anteriores.',
        ],
        deliverables: [
          '3 frames de onboarding en el mismo page.',
          'Indicador de progreso que muestra el estado correcto en cada pantalla.',
          'Link de Figma + captura de las 3 pantallas.',
        ],
        checklist: [
          'Las 3 pantallas comparten la misma estructura base.',
          'Cada pantalla comunica UN beneficio claro.',
          'Los dots de progreso están actualizados en cada frame.',
          'El último CTA es diferente al de los pasos intermedios.',
          'No hay más de 2 líneas de texto secundario.',
        ],
        commonMistakes: [
          'Pantallas con estructura diferente entre sí.',
          'Textos largos que nadie leerá.',
          'Olvidar actualizar el indicador de progreso en cada frame.',
          'Usar el mismo CTA en todos los pasos.',
          'Onboarding de más de 4 pasos.',
        ],
        difficulty: 2,
        timeLimitMinutes: 55,
        skills: ['mobile-ui', 'ux-flows', 'components'],
        rubric: [
          CRIT.consistencia(),
          CRIT.jerarquia(true),
          CRIT.flujo(),
          CRIT.ux(),
          CRIT.espaciado(),
          CRIT.tipografia(),
        ],
      },
    ),
    lesson(
      'Formularios de registro que no abandonan',
      'Diseñar un formulario de varios pasos con todos los estados y validación visual.',
      'Un formulario de registro es una negociación entre el producto y el usuario. Pide solo lo imprescindible. Cada campo extra reduce la tasa de conversión. Si necesitas muchos datos, usa un formulario en pasos.\n\nTodo campo tiene cinco estados que hay que diseñar: default, focus, filled, error y disabled. La validación debe ser en línea: el error aparece al salir del campo, no al enviar el formulario completo. Y el mensaje de error debe decir exactamente qué está mal y cómo arreglarlo.\n\nLos campos de contraseña merecen atención especial: toggle de visibilidad, indicador de fortaleza y requisitos visibles. Es donde más errores cometen los usuarios y donde más se abandona.',
      ['Campos y estados (default, focus, filled, error, disabled)', 'Validación en línea', 'Formulario en pasos', 'Indicador de fortaleza de contraseña', 'Mensajes de error accionables'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Estilos'],
      50,
      {
        title: 'Formulario de registro',
        brief: 'Diseña el formulario de registro de una plataforma de cursos online. Recoge: nombre, email, contraseña y plan (gratis / pro). Divide en 2 pasos si lo ves necesario.',
        context: 'El registro es el primer gate de conversión. Un formulario difícil o confuso = usuario perdido.',
        objective: 'Formulario claro con todos los estados de campo, validación visual y buen flujo.',
        targetUser: 'Persona que acaba de decidir probar la plataforma.',
        restrictions: [
          'Frame de 375px (móvil) o 768px (tablet), a tu elección.',
          'Todos los campos con mínimo 3 estados diseñados (default, error, filled).',
          'Mensaje de error accionable para el campo de email y contraseña.',
          'Indicador de fortaleza de contraseña.',
          'Auto Layout en todos los grupos de campos.',
        ],
        deliverables: [
          'Formulario completo con todos los campos.',
          'Al menos 2 frames mostrando estados de error en campos distintos.',
          'Frame con el estado "formulario completado correctamente".',
          'Link de Figma + captura.',
        ],
        checklist: [
          'Todos los campos tienen al menos estado default, error y filled.',
          'Los mensajes de error son específicos y accionables.',
          'El indicador de contraseña funciona visualmente.',
          'El botón de envío tiene estado disabled hasta completar el form.',
          'Spacing idéntico entre todos los campos.',
        ],
        commonMistakes: [
          'Diseñar solo el estado default.',
          'Mensaje de error genérico ("Campo inválido").',
          'Placeholder actuando como label (desaparece al escribir).',
          'Sin indicador de fortaleza en contraseña.',
          'Campos con alturas diferentes.',
        ],
        difficulty: 3,
        timeLimitMinutes: 65,
        skills: ['forms', 'mobile-ui', 'components', 'variants'],
        rubric: [
          CRIT.consistencia(),
          { name: 'Estados de campo', description: 'Todos los campos tienen al menos 3 estados diseñados y distinguibles.', isCritical: true },
          CRIT.espaciado(),
          CRIT.ux(true),
          CRIT.tipografia(),
          CRIT.autolayout(),
        ],
      },
    ),
    lesson(
      'Página de ajustes: claridad sin caos',
      'Organizar opciones de configuración en una interfaz escaneable y bien agrupada.',
      'Una página de settings es una de las más subestimadas del diseño de producto. Los usuarios la visitan cuando algo falla o quieren controlar algo. Si está desordenada, genera frustración.\n\nEl patrón estándar es una lista de secciones con cabecera de grupo, filas de ítem y un elemento de acción (toggle, flecha, label de valor). La consistencia entre filas es obligatoria. Si mezclas alturas, iconos distintos o márgenes irregulares, la pantalla parece rota.\n\nLos toggles necesitan los dos estados diseñados (on/off). Las filas que abren un submenú llevan flecha. Las que tienen un valor actual lo muestran inline. Cada grupo tiene un título de sección claro.',
      ['Agrupación de opciones', 'Filas de settings', 'Toggles (on/off)', 'Secciones con cabecera', 'Consistencia de lista'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Iconos'],
      40,
      {
        title: 'Página de ajustes',
        brief: 'Diseña la pantalla de ajustes de una app de finanzas personales. Incluye secciones de: Cuenta, Notificaciones, Privacidad y Sesión. Con al menos 3 tipos de fila distintos.',
        context: 'Los usuarios visitan settings cuando algo falla o quieren personalizar. Debe ser encontrable y claro.',
        objective: 'Pantalla de ajustes organizada, escaneable y consistente con 3 tipos de fila.',
        targetUser: 'Usuario que quiere cambiar algo concreto y encontrarlo en menos de 5 segundos.',
        restrictions: [
          'Frame de 375px.',
          'Mínimo 4 secciones con cabecera de grupo.',
          'Al menos 3 tipos de fila: toggle, fila con flecha y fila con valor actual.',
          'Todos los toggles con estado on y off diseñado.',
          'Auto Layout en toda la lista.',
        ],
        deliverables: [
          'Pantalla de ajustes completa.',
          'Detalle de los 3 tipos de fila en un frame aparte.',
          'Link de Figma + captura.',
        ],
        checklist: [
          'Las 4 secciones tienen cabecera visible.',
          'Todas las filas tienen la misma altura.',
          'Los toggles tienen estado on y off.',
          'Las filas con flecha las tienen; las que no, no.',
          'El espaciado entre grupos es mayor que dentro del grupo.',
        ],
        commonMistakes: [
          'Mezclar alturas de fila.',
          'Toggle solo en estado on.',
          'Sin distinción visual entre grupos.',
          'Iconos de distinto tamaño en la misma lista.',
          'Falta de cabecera de sección, todo parece una sola lista.',
        ],
        difficulty: 3,
        timeLimitMinutes: 55,
        skills: ['mobile-ui', 'components', 'variants', 'web-ui'],
        rubric: [
          CRIT.consistencia(),
          CRIT.jerarquia(true),
          CRIT.espaciado(),
          CRIT.autolayout(),
          { name: 'Tipos de fila', description: 'Hay al menos 3 tipos de fila diferenciados y correctamente aplicados en cada contexto.', isCritical: true },
        ],
      },
    ),
    lesson(
      'Checkout: el flujo más crítico del producto',
      'Diseñar un checkout de 3 pasos que minimice la fricción y maximice la confianza.',
      'El checkout es donde se pierde el dinero. Los estudios indican que más del 70% de los carritos se abandonan. La causa principal no es el precio: es la fricción. Formularios largos, pasos opacos y falta de señales de confianza.\n\nUn checkout bien diseñado tiene tres ingredientes: claridad en los pasos (dónde estoy, cuánto falta), resumen del pedido siempre visible y señales de confianza (candado, logotipos de pago). Nada de sorpresas en el último paso.\n\nEl diseño del paso de pago es crítico: el campo de tarjeta tiene un formato específico, los errores deben ser inmediatos y el CTA final debe transmitir seguridad. "Pagar 29€" es mejor que "Continuar".',
      ['Flujo de pasos (stepper)', 'Resumen de pedido', 'Señales de confianza', 'Campos de pago', 'Estado de confirmación', 'Empty states'],
      ['Auto Layout', 'Componentes', 'Prototyping'],
      50,
      {
        title: 'Checkout básico',
        brief: 'Diseña el checkout de una tienda de productos digitales. Tres pasos: (1) dirección de facturación, (2) método de pago, (3) confirmación. Frame de 375px.',
        context: 'Es el punto de mayor valor y mayor riesgo de abandono del producto.',
        objective: 'Flujo de checkout en 3 pasos claro, con resumen de pedido visible y señales de confianza.',
        targetUser: 'Cliente que ya ha decidido comprar y no quiere sorpresas.',
        restrictions: [
          'Frame de 375px por paso.',
          'Stepper visible en los 3 pasos indicando el progreso.',
          'Resumen del pedido visible en al menos los pasos 2 y 3.',
          'El CTA del paso final debe incluir el importe exacto.',
          'Pantalla de confirmación con estado de éxito claro.',
        ],
        deliverables: [
          '3 frames de los pasos del checkout.',
          '1 frame de pantalla de confirmación (success).',
          'Link de Figma + captura de los 4 frames.',
        ],
        checklist: [
          'El stepper muestra el paso actual en los 3 frames.',
          'El resumen del pedido está en los pasos 2 y 3.',
          'Hay al menos un elemento de confianza (candado, logo de pago).',
          'El CTA del paso 3 incluye el precio.',
          'La pantalla de éxito es inequívoca.',
        ],
        commonMistakes: [
          'Sin resumen del pedido visible: el usuario no sabe qué está comprando.',
          'CTA genérico "Continuar" en el paso de pago.',
          'Sin señales de confianza en el paso de tarjeta.',
          'Stepper que no muestra el progreso actual.',
          'Pantalla de confirmación idéntica a los pasos anteriores.',
        ],
        difficulty: 4,
        timeLimitMinutes: 65,
        skills: ['mobile-ui', 'forms', 'ux-flows', 'components'],
        rubric: [
          CRIT.ux(true),
          CRIT.flujo(),
          CRIT.consistencia(),
          CRIT.espaciado(),
          { name: 'Confianza y claridad en el pago', description: 'El paso de pago incluye señales de confianza y el CTA muestra el importe exacto.', isCritical: true },
          CRIT.jerarquia(),
        ],
      },
    ),
    lesson(
      'Mini app móvil: 5 pantallas coherentes',
      'Integrar todos los patrones de la fase en una app pequeña y cohesionada.',
      'Diseñar pantallas sueltas es fácil. Diseñar una app donde todo encaje es otra historia. La coherencia no es estética: es que el usuario siempre sepa dónde está y qué puede hacer.\n\nUna mini app de 5 pantallas necesita: navegación clara (tabs o back), estados consistentes en todos los componentes y un flujo lógico entre pantallas. Usa componentes reutilizables para que cambiar un botón lo cambie en todas partes.\n\nAntes de empezar a diseñar, define el flujo en papel o con wireframes básicos. ¿Qué hace el usuario en cada pantalla? ¿De dónde viene y adónde va? Sin eso, las pantallas serán bonitas pero no una app.',
      ['Navegación (tabs, back)', 'Flujo entre pantallas', 'Componentes compartidos', 'Coherencia de sistema', 'Empty states', 'Modales', 'Tabs'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Prototyping', 'Frames'],
      60,
      {
        title: 'Mini app móvil de 5 pantallas',
        brief: 'Diseña una mini app de seguimiento de lecturas (o el tema que elijas). Las 5 pantallas son: (1) Home con lista, (2) Detalle de ítem, (3) Búsqueda con empty state, (4) Añadir nuevo ítem (formulario), (5) Perfil / ajustes básicos.',
        context: 'Es el proyecto integrador de la fase. Demuestra que puedes hacer UI coherente y usable end-to-end.',
        objective: 'Mini app de 5 pantallas con navegación clara, componentes reutilizados y flujo lógico.',
        targetUser: 'Usuario que usa la app varios días a la semana para registrar y consultar contenido.',
        restrictions: [
          'Frame de 375px en todas las pantallas.',
          'Navegación inferior (tab bar) presente en las pantallas que corresponda.',
          'Usar los mismos componentes base (botón, card, input) en todas las pantallas.',
          'La pantalla de búsqueda debe incluir el estado empty state.',
          'Auto Layout en todos los layouts de pantalla.',
        ],
        deliverables: [
          '5 frames en el mismo page, nombrados con el nombre de la pantalla.',
          'Componentes base (botón, card, input) en una página "Components".',
          'Link de Figma + captura de las 5 pantallas juntas.',
        ],
        checklist: [
          'Las 5 pantallas comparten el mismo sistema de tipografía, color y spacing.',
          'Los componentes usados son instancias, no copias independientes.',
          'La tab bar está presente y activa en la pantalla correcta en cada frame.',
          'El empty state de búsqueda es informativo y no está vacío.',
          'El flujo de navegación es lógico (puedo ir de home a detalle a ajustes).',
        ],
        commonMistakes: [
          'Pantallas con estilos distintos entre sí.',
          'Duplicar elementos en lugar de usar instancias de componentes.',
          'Tab bar sin indicar la pantalla activa.',
          'Empty state con solo texto "No hay resultados".',
          'Formulario de la pantalla 4 sin estados de error.',
        ],
        difficulty: 4,
        timeLimitMinutes: 70,
        skills: ['mobile-ui', 'ux-flows', 'components', 'variants', 'forms', 'prototyping'],
        rubric: [
          CRIT.consistencia(),
          CRIT.componentes(true),
          CRIT.flujo(),
          CRIT.autolayout(true),
          CRIT.ux(),
          CRIT.profesionalidad(),
        ],
      },
    ),
  ],
};
