import { CRIT, type LessonSeed, type PhaseSeed } from './content-types.js';

function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  estimatedTimeMinutes: number,
  challenge: LessonSeed['challenge'],
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes, challenge };
}

export const phase08: PhaseSeed = {
  code: 'FASE 8',
  title: 'Prototipado',
  objective: 'Crear experiencias navegables y demostrables.',
  unlockedSkills: ['prototyping'],
  projects: [
    'Prototipo de app móvil',
    'Prototipo de landing',
    'Prototipo de dashboard',
    'Flujo completo clicable',
  ],
  lessons: [
    lesson(
      'Prototipo de app móvil',
      'Conectar pantallas con interacciones básicas y overlays.',
      'Un prototipo de app móvil convierte tus frames estáticos en algo que el cliente puede tocar. En Figma, las conexiones entre pantallas se crean desde el modo Prototype arrastrando un conector de un elemento al frame destino. Cada conexión define el trigger (On Click, On Drag), la acción (Navigate To, Open Overlay) y la animación (Instant, Dissolve, Smart Animate).\n\nLos overlays son la base de los modales, los bottom sheets y los menús emergentes. En lugar de navegar a una pantalla nueva, el overlay se superpone al frame actual y puede cerrarse al pulsar fuera. Esto replica el comportamiento real de las apps y hace el prototipo creíble.\n\nSmart Animate detecta capas con el mismo nombre entre dos frames y las anima automáticamente. Es la forma más rápida de simular transiciones de pantalla con movimiento real: un botón que crece, una card que vuela al detalle, un menú que se despliega. El secreto es mantener los nombres de capa coherentes entre frames.\n\nUna app navegable de 4-5 pantallas es suficiente para validar un flujo con usuarios reales. No necesitas diseñar todo el producto; necesitas demostrar el camino principal.',
      ['Conexiones de prototipo', 'Triggers', 'On Click', 'Navigate To', 'Open Overlay', 'Dissolve', 'Smart Animate', 'Bottom sheet', 'Modal'],
      ['Prototype mode', 'Connections', 'Overlays', 'Smart Animate'],
      55,
      {
        title: 'Prototipo de app móvil navegable',
        brief: 'Crea un prototipo de app móvil con al menos 4 pantallas conectadas, un overlay (modal o bottom sheet) y una transición con Smart Animate.',
        context: 'Tu cliente quiere ver cómo funciona la app antes de que el equipo de desarrollo empiece. El prototipo tiene que ser suficientemente real para probarse con usuarios.',
        objective: 'Entregar un prototipo navegable que cubra el flujo principal de la app con interacciones creíbles.',
        targetUser: 'Usuario final de la app móvil.',
        restrictions: [
          'Mínimo 4 frames conectados como pantallas.',
          'Al menos un overlay funcional (modal o bottom sheet).',
          'Al menos una transición con Smart Animate.',
          'Todas las conexiones configuradas desde elementos específicos, no desde el frame entero.',
        ],
        deliverables: [
          'Enlace al prototipo en modo presentación.',
          'Captura del panel de conexiones con al menos 3 rutas visibles.',
        ],
        checklist: [
          'El flujo principal se puede recorrer sin callejones sin salida.',
          'El overlay se abre y se puede cerrar.',
          'Smart Animate produce una transición visible y fluida.',
          'El prototipo funciona en la preview de móvil de Figma.',
        ],
        commonMistakes: [
          'Conectar el frame entero en vez del botón específico.',
          'Nombrar las capas de forma distinta entre frames, rompiendo Smart Animate.',
          'Olvidar añadir un botón de cierre al overlay.',
          'Usar Instant en todas las transiciones, eliminando toda sensación de movimiento.',
        ],
        difficulty: 3,
        timeLimitMinutes: 55,
        skills: ['prototyping', 'mobile-ui', 'ux-flows'],
        rubric: [
          CRIT.flujo(),
          { name: 'Prototipo navegable', description: 'El flujo principal es recorrible de inicio a fin sin bloqueos ni pantallas huérfanas.', isCritical: true },
          CRIT.ux(true),
          CRIT.consistencia(),
          CRIT.capas(),
        ],
      },
    ),
    lesson(
      'Prototipo de landing',
      'Simular scroll, elementos fijos y anclas de sección.',
      'Prototipar una landing tiene sus propias reglas. El frame debe tener la altura real del contenido, no la de la pantalla, y el overflow vertical tiene que estar en modo Scroll para que Figma simule el desplazamiento. Sin esto, el prototipo corta la página a mitad.\n\nLos elementos fijos, como la navbar, se marcan como "Fix position when scrolling" en el panel de diseño. Así permanecen visibles mientras el usuario se desplaza, igual que en un sitio web real. Es uno de los detalles que más impacta en la credibilidad del prototipo ante un cliente.\n\nLas anclas de sección permiten navegar desde un menú o un botón directamente a una parte concreta de la página. Se configura con la acción "Scroll To" apuntando a un frame concreto dentro de la misma página. Junto con las animaciones de transición suave, da una sensación de web real.\n\nLas variables en prototipos permiten ir un paso más allá: cambiar el estado de un componente (por ejemplo, abrir o cerrar un menú hamburguesa) sin navegar a otro frame. Esto reduce la cantidad de pantallas necesarias y hace el prototipo más mantenible.',
      ['Overflow scroll', 'Fix position when scrolling', 'Scroll To', 'Anclas', 'Variables en prototipo', 'Navbar fija', 'Smooth scroll'],
      ['Prototype mode', 'Overflow settings', 'Fix position', 'Variables'],
      60,
      {
        title: 'Landing con scroll y navbar fija',
        brief: 'Prototipa una landing de producto con scroll vertical real, navbar fija y al menos dos enlaces de ancla que desplazan a secciones concretas.',
        context: 'Vas a presentar la landing a un cliente que quiere sentir cómo funciona antes de que se desarrolle. El desplazamiento y la navbar fija son imprescindibles para que la demo sea convincente.',
        objective: 'Prototipo de landing con comportamiento de scroll web real y navegación por anclas funcional.',
        targetUser: 'Visitante que llega a la landing desde un anuncio.',
        restrictions: [
          'El frame principal debe tener overflow scroll activado.',
          'La navbar debe permanecer fija al hacer scroll.',
          'Al menos dos botones o enlaces con acción Scroll To a secciones distintas.',
          'La landing debe tener mínimo 3 secciones diferenciadas.',
        ],
        deliverables: [
          'Enlace al prototipo en modo presentación.',
          'Captura del panel de prototipo mostrando las conexiones de tipo Scroll To.',
        ],
        checklist: [
          'El scroll funciona y no corta el contenido.',
          'La navbar se mantiene visible al desplazarse.',
          'Los enlaces de ancla llevan a la sección correcta.',
          'La transición de scroll es suave, no instantánea.',
        ],
        commonMistakes: [
          'Frame con altura de viewport en vez de altura del contenido completo.',
          'Olvidar activar "Fix position when scrolling" en la navbar.',
          'Usar Navigate To en vez de Scroll To para los enlaces del menú.',
          'No testear el prototipo en la preview antes de entregarlo.',
        ],
        difficulty: 3,
        timeLimitMinutes: 60,
        skills: ['prototyping', 'web-ui', 'ux-flows'],
        rubric: [
          CRIT.flujo(),
          { name: 'Prototipo navegable', description: 'El scroll y la navbar fija funcionan correctamente en la preview de Figma.', isCritical: true },
          CRIT.ux(),
          CRIT.jerarquia(),
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'Prototipo de dashboard',
      'Prototipar estados, tabs y microinteracciones en interfaces complejas.',
      'Un dashboard es el tipo de interfaz que más se beneficia de un prototipo porque tiene muchos estados: tabs activos, filtros seleccionados, modales de detalle, gráficos con tooltip. Sin prototipo, el cliente no sabe qué espera ver cuando hace clic en cada elemento.\n\nLos tabs y los filtros se resuelven con Variables booleanas o de string que cambian el estado visible del componente. En vez de crear un frame por cada combinación posible, defines una variable y usas condicionales en el prototipo para mostrar u ocultar capas según su valor. Esto reduce drásticamente el número de frames necesarios.\n\nLas microinteracciones son los pequeños movimientos que dan vida a una interfaz: el hover de una fila de tabla, el estado de carga de un botón, el contador que sube. En Figma se simulan con transiciones rápidas (200-300ms) entre variantes de componente usando Smart Animate. No hace falta código; solo dos variantes y una conexión On Hover o After Delay.\n\nAntes de conectar todo, organiza los frames en un flujo claro en el canvas. Nombra cada frame con el patrón "Pantalla / Estado" para que las conexiones sean legibles. Un prototipo de dashboard desorganizado es tan difícil de mantener como código espagueti.',
      ['Variables en prototipo', 'Condicionales', 'Tabs interactivos', 'Microinteracciones', 'On Hover', 'After Delay', 'Smart Animate', 'Estados de componente', 'Variantes'],
      ['Prototype mode', 'Variables', 'Component variants', 'Smart Animate', 'Interactive components'],
      65,
      {
        title: 'Dashboard con tabs y microinteracciones',
        brief: 'Prototipa un dashboard con al menos 2 tabs funcionales que cambian el contenido visible, una microinteracción de hover en una fila o tarjeta, y un modal de detalle.',
        context: 'El equipo de producto necesita presentar el dashboard a stakeholders antes del sprint de desarrollo. Los tabs y el modal son las funcionalidades más comentadas en el brief.',
        objective: 'Prototipo de dashboard que demuestre la navegación entre tabs, microinteracciones creíbles y un flujo de detalle.',
        targetUser: 'Gestor o analista que usa el dashboard a diario.',
        restrictions: [
          'Los tabs deben cambiar el contenido sin navegar a otro frame (usar variables o interactive components).',
          'Al menos una microinteracción de hover con Smart Animate.',
          'Modal de detalle accesible desde al menos un elemento del dashboard.',
          'Frames nombrados con el patrón "Dashboard / Estado".',
        ],
        deliverables: [
          'Enlace al prototipo en modo presentación.',
          'Captura de las conexiones del componente interactivo (tabs o hover).',
        ],
        checklist: [
          'Los tabs cambian el contenido correctamente.',
          'El hover produce un cambio visual suave.',
          'El modal se abre y se cierra.',
          'Los frames están organizados y nombrados.',
        ],
        commonMistakes: [
          'Crear un frame separado por cada tab en vez de usar interactive components.',
          'Microinteracciones con duración demasiado larga (más de 500ms), que parecen lentas.',
          'Modal sin fondo semitransparente, que no separa visualmente del contenido.',
          'No probar el prototipo con un compañero antes de entregarlo.',
        ],
        difficulty: 4,
        timeLimitMinutes: 65,
        skills: ['prototyping', 'dashboards', 'ux-flows'],
        rubric: [
          CRIT.flujo(),
          { name: 'Prototipo navegable', description: 'Tabs, microinteracciones y modal funcionan en la preview sin errores de navegación.', isCritical: true },
          CRIT.ux(true),
          CRIT.consistencia(),
          CRIT.componentes(),
        ],
      },
    ),
    lesson(
      'Flujo completo clicable',
      'Construir y presentar un prototipo de producto completo listo para cliente.',
      'Un flujo completo es la suma de todas las pantallas de un camino de usuario de inicio a fin: desde que abre la app hasta que completa la tarea principal. Para presentarlo a un cliente necesitas que no haya callejones sin salida, que el flujo principal sea evidente y que el prototipo se pueda recorrer sin que tú tengas que explicar cada paso.\n\nLa preparación de la presentación es parte del trabajo de diseño. Usa el modo Presentation de Figma para ocultar el canvas y centrar la atención en el prototipo. Si el cliente va a navegar solo, añade hotspots visibles o indicaciones en pantalla. Si lo presentas tú, prepara un guion de 2-3 escenarios que quieres demostrar.\n\nLas anotaciones en el canvas, fuera de los frames, sirven para explicar decisiones a desarrolladores o a stakeholders que revisan el archivo directamente. Usa un color neutro y un estilo de texto diferente al del diseño para que no se confundan con el contenido real.\n\nEl checkpoint de esta fase es entregar un producto navegable que cualquier persona pueda recorrer sin instrucciones. Si necesitas explicar cómo funciona, el prototipo no está terminado.',
      ['Flujo de usuario completo', 'Modo presentación', 'Hotspots', 'Anotaciones', 'Guion de demo', 'Checkpoint de calidad', 'Entrega a cliente'],
      ['Prototype mode', 'Presentation mode', 'Hotspots', 'Comments', 'Share prototype'],
      70,
      {
        title: 'Flujo completo clicable listo para presentar',
        brief: 'Ensambla un prototipo completo que cubra el flujo principal de tu producto (mínimo 6 pantallas), sin callejones sin salida, listo para ser presentado a un cliente real o testado con usuarios.',
        context: 'Es el checkpoint de la fase. El producto puede ser cualquiera de los anteriores (app, landing, dashboard) o uno nuevo. El criterio de éxito es que otra persona pueda recorrerlo sin ayuda.',
        objective: 'Entregar un prototipo navegable, coherente y presentable que demuestre el dominio del prototipado en Figma.',
        targetUser: 'Cliente o usuario que recorre el prototipo sin instrucciones previas.',
        restrictions: [
          'Mínimo 6 frames en el flujo principal.',
          'Sin pantallas huérfanas ni callejones sin salida.',
          'Al menos una interacción avanzada: overlay, scroll con elemento fijo, microinteracción o variable.',
          'El prototipo debe compartirse con el modo "Anyone with the link can view" activado.',
          'Añadir al menos 3 anotaciones en el canvas explicando decisiones clave.',
        ],
        deliverables: [
          'Enlace al prototipo en modo presentación (acceso público).',
          'Captura del flujo completo en el canvas con anotaciones visibles.',
          'Un párrafo describiendo el escenario principal que demuestra el prototipo.',
        ],
        checklist: [
          'El flujo se puede recorrer de principio a fin sin bloqueos.',
          'Otra persona lo ha probado y ha llegado al final sin preguntar.',
          'Las transiciones son coherentes en toda la experiencia.',
          'Las anotaciones explican al menos una decisión de UX y una de interacción.',
          'El enlace compartido funciona en un navegador sin cuenta de Figma.',
        ],
        commonMistakes: [
          'Entregar el prototipo sin probarlo con nadie más.',
          'Tener pantallas del flujo secundario conectadas pero el flujo principal roto.',
          'Mezclar estilos de transición incompatibles que generan sensación de caos.',
          'Olvidar activar el acceso público al compartir el enlace.',
          'Anotaciones dentro de los frames que se confunden con el contenido.',
        ],
        difficulty: 4,
        timeLimitMinutes: 90,
        skills: ['prototyping', 'ux-flows', 'portfolio'],
        rubric: [
          CRIT.flujo(),
          { name: 'Prototipo navegable', description: 'El flujo completo es recorrible por cualquier persona sin instrucciones, de inicio a fin.', isCritical: true },
          CRIT.ux(true),
          CRIT.consistencia(),
          CRIT.profesionalidad(),
          CRIT.devready(),
        ],
      },
    ),
  ],
};
