import { CRIT, type LessonSeed, type PhaseSeed } from './content-types.js';

// Helper para crear lecciones de la Fase 11 con su reto.
function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  estimatedTimeMinutes: number,
  challenge: LessonSeed['challenge'],
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes, challenge };
}

export const phase11: PhaseSeed = {
  code: 'FASE 11',
  title: 'IA, plugins y workflows avanzados',
  objective: 'Usar herramientas avanzadas sin depender de ellas.',
  unlockedSkills: [],
  projects: [
    'Wireframe asistido por IA',
    'Contenido de interfaz mejorado',
    'Variaciones visuales generadas',
    'Sistema de diseño optimizado',
    'Comparativa manual vs asistida',
  ],
  lessons: [
    lesson(
      'Wireframe asistido por IA',
      'Usar Figma AI para arrancar una estructura y luego tomar el control.',
      'Figma AI puede generar wireframes de baja fidelidad a partir de un prompt. Es útil para saltar el bloqueo de la pantalla en blanco, pero la propuesta que genera es un punto de partida, no una solución. La IA no conoce a tu usuario, no ha leído el brief y no tiene criterio sobre la jerarquía que el negocio necesita.\n\nEl flujo correcto es: genera, observa, critica y reescribe. Acepta lo que tenga sentido de verdad (estructura básica, distribución de bloques) y rechaza lo que sea genérico o no encaje con el contexto. Documenta qué aceptaste y qué cambiaste.\n\nPlugins útiles para esta fase: Wireframe Designer, Autoflow, Mockup. Úsalos como aceleradores, no como diseñadores subcontratados.',
      ['Figma AI', 'Wireframing asistido', 'Prompt de diseño', 'Criterio editorial'],
      ['Figma AI', 'Wireframe Designer (plugin)', 'Autoflow (plugin)'],
      50,
      {
        title: 'Wireframe asistido por IA',
        brief: 'Genera un wireframe de una pantalla de inicio de app con Figma AI y refínalo manualmente hasta que sea correcto.',
        context: 'El cliente quiere ver la estructura de la app antes de definir el visual. Tienes 48 horas y empiezas desde cero.',
        objective: 'Obtener un wireframe funcional que refleje el brief real, no una plantilla genérica.',
        targetUser: 'Usuario de 25-40 años que accede a la app por primera vez.',
        restrictions: [
          'Debes usar Figma AI al menos una vez para generar la estructura inicial.',
          'Obligatorio documentar en una nota qué partes aceptaste de la IA y cuáles modificaste.',
          'No entregar el output de la IA sin modificar.',
          'Máximo 3 secciones en el wireframe.',
        ],
        deliverables: [
          'Frame de wireframe finalizado.',
          'Nota dentro del archivo con el log de cambios (aceptado / rechazado / modificado).',
          'Link + captura.',
        ],
        checklist: [
          'El wireframe responde al brief, no es una plantilla genérica.',
          'Existe una nota con el log de decisiones sobre la IA.',
          'La jerarquía de contenido es legible.',
          'Capas nombradas correctamente.',
        ],
        commonMistakes: [
          'Entregar el wireframe exactamente como lo generó la IA.',
          'No documentar qué se cambió.',
          'Jerarquía plana sin diferencia visual entre bloques.',
        ],
        difficulty: 3,
        timeLimitMinutes: 55,
        skills: ['ux-flows', 'design-systems'],
        rubric: [
          CRIT.jerarquia(true),
          CRIT.capas(),
          {
            name: 'Criterio sobre la IA',
            description: 'El alumno justifica explícitamente qué aceptó y qué rechazó del output de la IA, demostrando que tomó decisiones con criterio propio.',
            isCritical: true,
          },
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'Mejorar contenido de interfaz con IA',
      'Usar la IA para generar copy realista y evaluar su calidad antes de integrarlo.',
      'El texto de relleno (Lorem Ipsum) mata el realismo de un diseño. Figma AI y plugins como Content Reel o Unsplash permiten sustituirlo por contenido representativo: nombres reales, títulos de producto, descripciones, imágenes contextualmente apropiadas.\n\nEl criterio importa más que la velocidad. Un título generado por IA puede ser demasiado largo, demasiado genérico o no alineado con el tono de marca. Antes de aceptarlo, pregúntate: ¿encaja con el tono de voz del producto? ¿La longitud del texto es la que va a aparecer en producción?\n\nUsa también plugins de accesibilidad como Contrast o A11y Annotation Kit para verificar que el contenido insertado sigue cumpliendo los ratios de contraste. El contenido real a veces rompe un diseño que parecía correcto con Lorem Ipsum.',
      ['Copy generado por IA', 'Contenido realista', 'Tono de voz', 'Content Reel', 'Contraste'],
      ['Figma AI', 'Content Reel (plugin)', 'Unsplash (plugin)', 'Contrast (plugin)'],
      45,
      {
        title: 'Contenido de interfaz mejorado',
        brief: 'Sustituye todo el Lorem Ipsum de una pantalla existente por contenido realista generado con ayuda de la IA, y valida que el diseño sigue funcionando.',
        context: 'Preparas una pantalla de producto para presentarla al cliente. El Lorem Ipsum hace que el cliente no entienda el flujo real.',
        objective: 'Pantalla con contenido realista, tono correcto y contraste validado.',
        targetUser: 'Cliente que evalúa el diseño por primera vez.',
        restrictions: [
          'Cero Lorem Ipsum en la entrega.',
          'El copy debe tener el tono del producto definido en el brief.',
          'Contraste verificado con plugin tras insertar el contenido.',
          'Imágenes contextualmente relevantes, no fotos de stock aleatorias.',
        ],
        deliverables: [
          'Pantalla con contenido real.',
          'Captura del resultado del plugin de contraste.',
          'Link + captura final.',
        ],
        checklist: [
          'No hay Lorem Ipsum.',
          'El copy encaja con el tono del producto.',
          'El contraste pasa el test.',
          'Las imágenes son coherentes con el contexto.',
        ],
        commonMistakes: [
          'Aceptar el primer texto generado sin leerlo.',
          'Insertar imágenes de stock que no encajan con el contexto.',
          'Olvidar validar el contraste tras el cambio de contenido.',
        ],
        difficulty: 3,
        timeLimitMinutes: 45,
        skills: ['design-systems', 'components'],
        rubric: [
          CRIT.tipografia(),
          CRIT.color(),
          CRIT.accesibilidad(),
          {
            name: 'Criterio sobre la IA',
            description: 'El copy y las imágenes elegidos son apropiados para el contexto y el tono del producto, no son el primer resultado genérico que ofreció la IA.',
            isCritical: true,
          },
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'Generar variaciones visuales con plugins',
      'Usar la IA para explorar variaciones de color, tipografía e iconografía sin perder el sistema.',
      'Explorar variaciones visuales manualmente es lento. Plugins como Styles Organizer, Themer o la generación de paletas de Figma AI permiten probar combinaciones en minutos. Sin embargo, una variación visualmente atractiva no es necesariamente correcta: puede romper la accesibilidad, perder la identidad de marca o no encajar con los tokens ya definidos.\n\nEl proceso correcto: genera variaciones, filtra con criterio (contraste, coherencia con el sistema, identidad de marca), elige la más sólida y documenta por qué la elegiste. La IA genera opciones; tú decides cuál es correcta y por qué.\n\nUsa plugins de iconos (Iconify, Material Symbols) para explorar familias de iconos consistentes. Un icono suelto de otra familia rompe la consistencia del sistema.',
      ['Variaciones de color', 'Paletas generadas por IA', 'Iconografía', 'Themer', 'Iconify', 'Tokens de color'],
      ['Figma AI', 'Themer (plugin)', 'Iconify (plugin)', 'Styles Organizer (plugin)'],
      40,
      {
        title: 'Variaciones visuales generadas',
        brief: 'Genera al menos 3 variaciones de color para un componente o pantalla existente usando plugins o Figma AI, elige la mejor y justifica la decisión.',
        context: 'El equipo quiere explorar una dirección de color alternativa antes de comprometerse con el sistema actual.',
        objective: 'Presentar variaciones fundamentadas, no aleatorias, con la elección documentada.',
        targetUser: 'Equipo de producto que evalúa la dirección visual.',
        restrictions: [
          'Mínimo 3 variaciones generadas.',
          'Cada variación debe pasar el test de contraste WCAG AA.',
          'Elegir solo una y documentar el criterio de elección.',
          'No mezclar familias de iconos distintas.',
        ],
        deliverables: [
          'Frame con las 3 variaciones.',
          'Nota con el criterio de elección.',
          'Link + captura.',
        ],
        checklist: [
          'Hay 3 variaciones diferenciadas.',
          'Todas pasan el contraste AA.',
          'La elección está documentada con argumentos.',
          'Los iconos son de la misma familia.',
        ],
        commonMistakes: [
          'Elegir la variación más bonita sin comprobar el contraste.',
          'Mezclar estilos de icono de distintas familias.',
          'No documentar por qué se eligió una opción.',
        ],
        difficulty: 3,
        timeLimitMinutes: 45,
        skills: ['design-systems', 'tokens', 'color'],
        rubric: [
          CRIT.color(),
          CRIT.accesibilidad(),
          CRIT.consistencia(),
          {
            name: 'Criterio sobre la IA',
            description: 'El alumno justifica la variación elegida con argumentos de accesibilidad, identidad y sistema, no solo por preferencia estética.',
            isCritical: true,
          },
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'Optimizar el sistema de diseño con automatización',
      'Usar plugins de tokens, organización y auditoría para mantener el sistema limpio y escalable.',
      'Un sistema de diseño crece y se desordena. Plugins como Token Studio permiten gestionar design tokens conectados a código. Plugins de auditoría como Design Lint o Find & Replace detectan estilos desconectados, colores hardcoded y capas sin nombre que degradan el sistema.\n\nLa automatización aquí no diseña: audita. La IA puede sugerir agrupaciones de tokens o detectar inconsistencias, pero la arquitectura del sistema la decide el diseñador. Un token mal nombrado o mal agrupado genera deuda técnica en el equipo de desarrollo.\n\nBuenas prácticas: nombra los tokens por rol (color/brand/primary), no por valor (color/blue-500). Organiza las librerías con páginas separadas por tipo (foundations, components, patterns). Revisa el sistema con Design Lint antes de cada entrega importante.',
      ['Design tokens', 'Token Studio', 'Design Lint', 'Auditoría del sistema', 'Naming de tokens'],
      ['Token Studio (plugin)', 'Design Lint (plugin)', 'Find & Replace (plugin)', 'Variables de Figma'],
      50,
      {
        title: 'Sistema de diseño optimizado',
        brief: 'Audita un sistema de diseño propio o de práctica con Design Lint, corrige los errores encontrados y documenta los tokens principales con nombres por rol.',
        context: 'El sistema de diseño lleva meses creciendo sin revisión. Antes de dárselo al equipo de desarrollo, necesita una auditoría.',
        objective: 'Sistema limpio, con tokens nombrados por rol y sin estilos desconectados.',
        targetUser: 'Equipo de desarrollo que consumirá los tokens.',
        restrictions: [
          'Usar Design Lint y corregir al menos el 80% de los errores detectados.',
          'Tokens nombrados por rol, no por valor.',
          'Capas y componentes nombrados correctamente.',
          'Librerías organizadas por tipo.',
        ],
        deliverables: [
          'Captura del informe de Design Lint antes y después.',
          'Frame con los tokens organizados por rol.',
          'Link al archivo auditado.',
        ],
        checklist: [
          'Design Lint muestra menos errores tras la corrección.',
          'Los tokens siguen la convención de nombre por rol.',
          'No hay colores hardcoded fuera del sistema.',
          'Las capas están nombradas.',
        ],
        commonMistakes: [
          'Nombrar tokens por su valor visual (azul-500) en lugar de por su rol (brand/primary).',
          'Ignorar los errores de Design Lint que parecen menores.',
          'No separar foundations de components en la librería.',
        ],
        difficulty: 4,
        timeLimitMinutes: 60,
        skills: ['design-systems', 'tokens', 'components', 'variables'],
        rubric: [
          CRIT.componentes(true),
          CRIT.consistencia(),
          CRIT.capas(),
          {
            name: 'Criterio sobre la IA',
            description: 'La arquitectura de tokens y la organización del sistema son decisiones del diseñador, no del plugin. El alumno demuestra que entiende el sistema que ha construido.',
            isCritical: true,
          },
          CRIT.devready(true),
        ],
      },
    ),
    lesson(
      'Manual vs asistido: el diseñador decide',
      'Comparar un diseño hecho a mano con uno asistido por IA para entender qué aporta cada enfoque.',
      'La comparativa directa entre diseño manual y diseño asistido por IA es el ejercicio más honesto para entender el valor real de las herramientas. El diseño asistido es más rápido para explorar pero más impreciso en el detalle. El diseño manual es más lento pero revela problemas de UX que la IA no detecta.\n\nEste ejercicio no busca que la IA gane. Busca que el diseñador sepa cuándo usar cada enfoque: IA para exploración inicial, baja fidelidad, generación de contenido o auditorías; criterio manual para decisiones de jerarquía, flujo, accesibilidad y coherencia con el sistema.\n\nUn diseñador que sabe usar herramientas avanzadas con criterio es más valioso que uno que evita la IA por principio o que la usa sin filtro. La competencia no está en la herramienta, está en el juicio.',
      ['Diseño manual vs asistido', 'Criterio de diseñador', 'Cuándo usar IA', 'Flujo de trabajo híbrido'],
      ['Figma AI', 'Plugins de auditoría', 'Figma (herramienta base)'],
      55,
      {
        title: 'Comparativa manual vs asistida',
        brief: 'Diseña la misma pantalla dos veces: una completamente a mano y otra con ayuda máxima de IA y plugins. Luego presenta cuál es mejor y por qué.',
        context: 'Checkpoint de fase. Demuestras que sabes usar la IA sin depender de ella.',
        objective: 'Entender las ventajas y limitaciones reales de cada enfoque y argumentar la elección.',
        targetUser: 'Tú mismo como diseñador que toma decisiones de workflow.',
        restrictions: [
          'La versión manual no puede usar Figma AI ni plugins generativos.',
          'La versión asistida debe usar al menos 2 herramientas de IA o plugins.',
          'Ambas versiones deben resolver el mismo brief.',
          'Obligatorio entregar un análisis escrito de mínimo 5 puntos comparados.',
        ],
        deliverables: [
          'Dos frames con la misma pantalla (manual y asistida).',
          'Análisis escrito comparando ambas versiones (mínimo 5 puntos).',
          'Conclusión sobre cuándo usarías cada enfoque.',
          'Link + captura.',
        ],
        checklist: [
          'Las dos versiones resuelven el mismo brief.',
          'El análisis tiene al menos 5 puntos comparados.',
          'La conclusión es específica, no genérica.',
          'Se indica claramente qué herramientas se usaron en la versión asistida.',
        ],
        commonMistakes: [
          'Análisis superficial del tipo "la IA es más rápida".',
          'No respetar las restricciones de la versión manual.',
          'Conclusión genérica sin aplicación a un contexto de trabajo real.',
        ],
        difficulty: 4,
        timeLimitMinutes: 80,
        skills: ['ux-flows', 'design-systems', 'portfolio'],
        rubric: [
          CRIT.jerarquia(),
          CRIT.ux(true),
          CRIT.profesionalidad(),
          {
            name: 'Criterio sobre la IA',
            description: 'El análisis comparativo demuestra comprensión real de cuándo la IA aporta valor y cuándo el criterio manual es insustituible. La conclusión es específica y aplicable.',
            isCritical: true,
          },
          CRIT.flujo(),
        ],
      },
    ),
  ],
};
