import { CRIT, type LessonSeed, type PhaseSeed } from './content-types.js';

function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  estimatedTimeMinutes: number,
  challenge: LessonSeed['challenge'],
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes, challenge };
}

export const phase09: PhaseSeed = {
  code: 'FASE 9',
  title: 'Producto digital avanzado',
  objective: 'Diseñar productos complejos.',
  unlockedSkills: ['dashboards', 'saas-ui', 'ux-flows', 'forms', 'design-systems'],
  projects: [
    'Dashboard SaaS',
    'Panel de administración',
    'CRM simple',
    'App de gestión',
    'Plataforma tipo curso',
  ],
  lessons: [
    lesson(
      'Dashboard SaaS: métricas y datos en tiempo real',
      'Diseñar un dashboard analítico con métricas clave, gráficos, tablas y estados de carga.',
      'Un dashboard SaaS no es una colección de gráficos bonitos: es una herramienta de decisión. Cada métrica debe responder una pregunta concreta del usuario. Antes de poner un KPI en pantalla, pregunta: ¿qué acción provoca este dato? Si no hay respuesta, sobra.\n\nLa jerarquía visual es crítica. Los KPIs principales van arriba y ocupan más espacio; los detalles van debajo. Usa variaciones de peso tipográfico, tamaño y color para separar el dato del contexto, no decoración. Un número grande con una etiqueta pequeña comunica más que una card con sombras y gradientes.\n\nLos estados de carga y error son parte del diseño, no afterthoughts. Un skeleton loader correcto tiene la misma estructura que el contenido real. Un estado de error debe decir qué falló y qué puede hacer el usuario. Un estado vacío en una tabla recién creada no es igual que uno donde el filtro activo descartó todos los resultados: son mensajes distintos.\n\nLos gráficos deben ser legibles sin interacción. Etiqueta los ejes, usa colores accesibles, y proporciona tooltips claros. Nunca uses un gráfico de tarta con más de 4 segmentos: usa una tabla.',
      ['KPIs', 'Skeleton loaders', 'Estados vacíos y de error', 'Jerarquía de datos', 'Gráficos accesibles', 'Tablas de datos'],
      ['Auto Layout', 'Variables', 'Componentes', 'Tokens'],
      90,
      {
        title: 'Dashboard SaaS',
        brief: 'Diseña el dashboard principal de "Pulso", una plataforma SaaS B2B de analítica de ventas. La pantalla debe mostrar: 4 KPIs en la cabecera (ingresos del mes, nuevos clientes, churn rate, NPS), un gráfico de línea de ingresos de los últimos 12 meses con selector de período, una tabla de las 10 últimas transacciones con columnas ordenables (cliente, importe, estado, fecha, acciones), un panel lateral con los 5 productos más vendidos y un selector de rango de fechas global que afecte a todos los módulos. Diseña también el estado skeleton de carga, el estado de error de red y el estado vacío cuando no hay datos en el rango seleccionado.',
        context: 'El equipo de ventas abre este dashboard cada mañana. Necesitan ver de un vistazo si el negocio va bien y detectar anomalías antes de la reunión de las 9h.',
        objective: 'Crear un dashboard denso pero legible, con jerarquía clara, estados completos y datos realistas.',
        targetUser: 'Director de ventas B2B, 35-50 años, acostumbrado a Excel y Salesforce.',
        restrictions: [
          'Modo claro obligatorio, modo oscuro opcional.',
          'Todos los componentes de datos con estado skeleton, error y vacío.',
          'Tabla con mínimo 5 columnas y acciones por fila.',
          'Ningún gráfico de tarta.',
          'Colores de estado semánticos (verde/rojo/amarillo) coherentes en toda la pantalla.',
          'Tipografía numérica monoespaciada para los KPIs.',
        ],
        deliverables: [
          'Frame desktop (1440px) del dashboard en estado cargado con datos realistas.',
          'Frame del estado skeleton de carga.',
          'Frame del estado de error de red con acción de reintento.',
          'Frame del estado vacío para rango sin datos.',
          'Link de Figma + captura PNG.',
        ],
        checklist: [
          'Los 4 KPIs tienen jerarquía clara: número grande, etiqueta pequeña, delta de período.',
          'La tabla tiene encabezados, filas alternadas o separadores, y acciones por fila.',
          'El skeleton replica la estructura exacta del estado cargado.',
          'El error muestra qué pasó y ofrece una acción de recuperación.',
          'El estado vacío diferencia "sin datos en rango" de "sin datos nunca".',
          'Los colores de estado (éxito, error, alerta) son coherentes en todo el diseño.',
          'El selector de período está visualmente conectado al contenido que filtra.',
        ],
        commonMistakes: [
          'KPIs sin deltas ni contexto comparativo: un número solo no comunica nada.',
          'Skeleton con formas que no corresponden al contenido real.',
          'Tabla con columnas de ancho fijo que se rompen con datos largos.',
          'Estados de error genéricos sin acción para el usuario.',
          'Usar el mismo color de estado para conceptos distintos.',
          'Gráficos sin escala ni etiquetas de eje.',
        ],
        difficulty: 4,
        timeLimitMinutes: 90,
        skills: ['dashboards', 'saas-ui', 'ux-flows'],
        rubric: [
          CRIT.jerarquia(true),
          CRIT.ux(true),
          CRIT.consistencia(),
          { name: 'Estados completos', description: 'Skeleton, error y vacío diseñados y coherentes con el estado cargado.', isCritical: true },
          { name: 'Datos realistas', description: 'Los datos de ejemplo son creíbles y permiten evaluar la legibilidad real del diseño.' },
          CRIT.tipografia(),
          CRIT.color(),
          CRIT.devready(),
        ],
      },
    ),
    lesson(
      'Panel de administración: roles, permisos y gestión de usuarios',
      'Diseñar un panel admin con gestión de usuarios, roles diferenciados y acciones destructivas protegidas.',
      'Un panel de administración no es un dashboard: es una herramienta de control. Sus usuarios son internos, técnicos o con privilegios elevados, y las acciones que ejecutan tienen consecuencias reales e irreversibles. El diseño debe reflejar esto: las acciones destructivas deben costar un clic extra, no uno de menos.\n\nLa gestión de roles y permisos es uno de los problemas de UX más complejos. El usuario necesita entender qué puede hacer cada rol, ver el estado actual de permisos de cada cuenta y modificarlos sin miedo a romper algo. Los patrones de tabla con acciones inline, modales de confirmación y mensajes de éxito/error son la base.\n\nLas tablas de usuarios grandes requieren búsqueda, filtros combinables (por rol, estado, fecha de registro), paginación o scroll infinito y selección múltiple para acciones en lote. Un buen filtro activo debe ser visible y reversible con un clic.\n\nLos estados vacíos en un panel admin tienen contexto: "No hay usuarios con ese filtro" es diferente a "Aún no has invitado a nadie". Las acciones de invitación, suspensión, cambio de rol y eliminación deben tener confirmación proporcional a su impacto.',
      ['Gestión de roles', 'Tablas con filtros', 'Acciones destructivas', 'Confirmaciones de seguridad', 'Permisos inline', 'Acciones en lote'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Overlays/modales'],
      95,
      {
        title: 'Panel de administración',
        brief: 'Diseña el panel de administración de usuarios de "Vantage", una plataforma SaaS empresarial con tres roles: Admin, Editor y Viewer. La interfaz debe incluir: una tabla de usuarios con columnas (avatar, nombre, email, rol, estado activo/suspendido, último acceso, acciones), búsqueda en tiempo real por nombre o email, filtros combinables por rol y estado, selección múltiple con barra de acciones en lote (suspender, cambiar rol, eliminar), modal de invitación de nuevo usuario con selector de rol y mensaje personalizable, modal de confirmación para acciones destructivas (eliminar cuenta), panel lateral de detalle de usuario con historial de actividad y opción de cambio de rol con advertencia de impacto, y un estado vacío contextual para búsquedas sin resultados.',
        context: 'El administrador de IT de una empresa de 200 personas gestiona altas, bajas y cambios de rol desde este panel. Las acciones incorrectas bloquean el acceso de empleados a herramientas críticas.',
        objective: 'Panel admin funcional, seguro y eficiente para gestión de usuarios con roles diferenciados.',
        targetUser: 'Administrador de IT o responsable de operaciones, sin perfil técnico pero con permisos totales.',
        restrictions: [
          'Las acciones destructivas deben requerir confirmación explícita (no solo un clic).',
          'El rol de cada usuario debe ser visible sin abrir detalle.',
          'Los filtros activos deben mostrarse como chips eliminables.',
          'La selección múltiple debe mostrar cuántos elementos están seleccionados.',
          'El modal de eliminación debe pedir confirmación escribiendo el nombre o email.',
          'Los estados de usuario (activo, suspendido, pendiente de aceptar invitación) deben ser visualmente distintos.',
        ],
        deliverables: [
          'Frame de la tabla principal con datos realistas (mínimo 8 usuarios, roles mixtos).',
          'Frame con filtros activos y resultados filtrados.',
          'Frame con selección múltiple y barra de acciones en lote.',
          'Modal de invitación de nuevo usuario.',
          'Modal de confirmación de eliminación.',
          'Panel lateral de detalle de usuario.',
          'Estado vacío para búsqueda sin resultados.',
          'Link de Figma + captura PNG.',
        ],
        checklist: [
          'Los tres roles son visualmente distinguibles en la tabla.',
          'Los filtros activos se muestran como chips con botón de eliminar.',
          'La selección múltiple muestra el contador de seleccionados.',
          'El modal de eliminación tiene fricción deliberada (escribir confirmación).',
          'El panel lateral tiene información útil, no solo repetir la fila.',
          'El estado vacío ofrece una acción relevante (limpiar filtros o invitar usuario).',
          'Las acciones inline (editar, suspender, eliminar) tienen jerarquía visual coherente.',
        ],
        commonMistakes: [
          'Acciones destructivas con el mismo peso visual que acciones seguras.',
          'Filtros que no muestran cuáles están activos.',
          'Modal de confirmación con solo "¿Estás seguro? Sí / No".',
          'Tabla sin estados de fila diferenciados para activo/suspendido.',
          'Panel lateral que duplica información de la tabla sin añadir valor.',
          'Ignorar el estado "pendiente de aceptar invitación".',
        ],
        difficulty: 5,
        timeLimitMinutes: 100,
        skills: ['saas-ui', 'ux-flows', 'dashboards'],
        rubric: [
          CRIT.ux(true),
          CRIT.consistencia(),
          { name: 'Seguridad UX', description: 'Las acciones destructivas tienen confirmación proporcional a su impacto y no son accidentalmente ejecutables.', isCritical: true },
          { name: 'Gestión de filtros', description: 'Los filtros activos son visibles, combinables y reversibles sin perder el contexto.', isCritical: true },
          CRIT.jerarquia(),
          CRIT.flujo(),
          CRIT.capas(),
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'CRM simple: contactos, pipeline y seguimiento',
      'Diseñar un CRM ligero con vistas de contacto, pipeline de ventas Kanban y registro de actividad.',
      'Un CRM es una de las aplicaciones más complejas de diseñar porque combina múltiples vistas del mismo dato: un contacto puede verse en una ficha, en una fila de tabla, en una tarjeta Kanban y en un historial de actividad. La consistencia entre estas vistas es el mayor reto técnico y de diseño.\n\nEl pipeline Kanban tiene sus propias reglas: las columnas representan etapas, las tarjetas son oportunidades, y el drag-and-drop es la interacción principal. Las tarjetas deben mostrar información suficiente para tomar decisiones sin abrir el detalle: nombre del contacto, importe estimado, probabilidad y días en etapa. Una tarjeta que lleva más de 30 días sin moverse es una alerta.\n\nLa búsqueda y el filtrado en un CRM son críticos. Los comerciales buscan por nombre, empresa, estado, responsable asignado y rango de fechas. Los filtros deben ser rápidos y combinables. Los resultados deben mantenerse al navegar entre vistas.\n\nEl registro de actividad (llamadas, emails, reuniones, notas) es el corazón del CRM. Cada interacción debe ser registrable en 3 clics o menos. El historial debe ser cronológico, diferenciado por tipo y filtrable.',
      ['Pipeline Kanban', 'Fichas de contacto', 'Registro de actividad', 'Búsqueda y filtros en CRM', 'Consistencia multi-vista', 'Tarjetas de oportunidad'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Prototyping'],
      100,
      {
        title: 'CRM simple',
        brief: 'Diseña el módulo principal de "Nexo CRM", una herramienta para equipos de ventas de hasta 50 personas. La aplicación debe incluir: vista de lista de contactos con tabla (nombre, empresa, cargo, estado del lead, responsable, última interacción, acciones), búsqueda global y filtros por estado, responsable y fecha de última interacción, ficha de contacto con datos personales, historial de actividad cronológico y acceso rápido para registrar nueva actividad, vista Kanban del pipeline con columnas (Prospecto, Contactado, Propuesta enviada, Negociación, Cerrado ganado, Cerrado perdido), tarjetas de oportunidad con importe, probabilidad y días en etapa, y modal de registro de actividad con selector de tipo (llamada, email, reunión, nota) y campos contextuales según el tipo.',
        context: 'Un equipo comercial de 15 personas gestiona 400 contactos activos. Cada comercial ve solo sus contactos; los managers ven el equipo completo.',
        objective: 'CRM ligero con vistas coherentes, pipeline visual y registro de actividad rápido.',
        targetUser: 'Comercial B2B de 25-45 años, en constante movimiento, que necesita registrar actividad desde cualquier dispositivo.',
        restrictions: [
          'La vista lista y la vista Kanban deben compartir los mismos filtros.',
          'El Kanban debe mostrar el importe total por columna.',
          'Las tarjetas con más de 14 días sin actividad deben tener indicador visual.',
          'El modal de nueva actividad debe cambiar sus campos según el tipo seleccionado.',
          'Los contactos de otros comerciales deben verse pero no editarse (rol Manager vs Comercial).',
          'La búsqueda global debe funcionar en ambas vistas.',
        ],
        deliverables: [
          'Frame de la vista lista de contactos con datos realistas.',
          'Frame de la vista Kanban del pipeline con oportunidades en distintas etapas.',
          'Frame de la ficha de contacto con historial de actividad.',
          'Modal de registro de actividad (muestra el tipo "llamada" con sus campos).',
          'Frame del estado vacío del pipeline para un comercial nuevo.',
          'Link de Figma + captura PNG.',
        ],
        checklist: [
          'La tabla de contactos tiene columnas relevantes para ventas, no datos genéricos.',
          'El Kanban muestra importe total por columna y días en etapa por tarjeta.',
          'Las tarjetas inactivas tienen indicador visual claro.',
          'La ficha de contacto tiene historial cronológico con iconos por tipo de actividad.',
          'El modal de actividad cambia los campos según el tipo (llamada = duración; email = asunto; reunión = lugar).',
          'La diferencia de permisos entre Comercial y Manager es visible en el diseño.',
        ],
        commonMistakes: [
          'Tarjetas Kanban con demasiada información que no cabe en el ancho de la columna.',
          'Historial de actividad sin distinción visual entre tipos.',
          'Modal de actividad con todos los campos visibles siempre, independientemente del tipo.',
          'Pipeline sin importes ni métricas de tiempo.',
          'Ignorar el estado "Cerrado perdido" en el Kanban.',
          'Filtros que solo funcionan en una vista.',
        ],
        difficulty: 5,
        timeLimitMinutes: 100,
        skills: ['saas-ui', 'ux-flows', 'dashboards'],
        rubric: [
          CRIT.ux(true),
          CRIT.consistencia(),
          { name: 'Coherencia multi-vista', description: 'La información de un contacto/oportunidad es coherente entre la tabla, el Kanban y la ficha de detalle.', isCritical: true },
          CRIT.flujo(),
          { name: 'Pipeline Kanban', description: 'Las columnas, tarjetas e indicadores de tiempo communican el estado del pipeline sin necesidad de abrir detalles.' },
          CRIT.jerarquia(),
          CRIT.profesionalidad(),
          CRIT.devready(),
        ],
      },
    ),
    lesson(
      'App de gestión: proyectos, tareas y equipos',
      'Diseñar una app de gestión de proyectos con vistas múltiples, asignaciones y seguimiento de progreso.',
      'Las apps de gestión de proyectos como Asana, Linear o Notion tienen en común que el mismo dato (una tarea) puede representarse de cuatro formas distintas: lista, tablero Kanban, timeline y calendario. El reto de diseño no es inventar cada vista, sino mantener la coherencia y garantizar que las acciones principales están a menos de dos clics en cualquier vista.\n\nLa asignación de tareas y la visibilidad del trabajo del equipo son las funciones más usadas. Un buen diseño muestra de un vistazo quién tiene sobrecarga, qué tareas están bloqueadas y qué está próximo a vencer. Los avatares, los colores de prioridad y las fechas límite deben comunicar este estado sin necesidad de leer cada tarea.\n\nEl progreso del proyecto necesita métricas simples: porcentaje completado, número de tareas por estado y tiempo restante. Estas métricas deben actualizarse automáticamente y ser visibles desde la vista de listado de proyectos, sin entrar en cada proyecto.\n\nLos estados de las tareas (pendiente, en progreso, bloqueada, en revisión, completada) deben tener representación visual consistente en todas las vistas. Una tarea bloqueada es diferente a una pendiente: tiene una causa y posiblemente un responsable de desbloquear.',
      ['Vistas múltiples de tarea', 'Asignación de equipo', 'Indicadores de progreso', 'Estados de tarea', 'Tareas bloqueadas', 'Timeline y fechas'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Variables'],
      95,
      {
        title: 'App de gestión',
        brief: 'Diseña el módulo de proyectos de "Orbit", una app de gestión de trabajo para equipos de diseño y desarrollo de 5-30 personas. La aplicación debe incluir: listado de proyectos con tarjeta de proyecto (nombre, cliente, progreso en porcentaje, miembros asignados, fecha límite, estado), vista de tareas en modo lista con columnas (tarea, responsable, prioridad, estado, fecha límite, estimación en horas), vista Kanban de las mismas tareas (columnas: Backlog, En progreso, En revisión, Bloqueado, Completado), panel de detalle de tarea con descripción, subtareas, historial de comentarios, archivos adjuntos y log de cambios de estado, selector de prioridad con 4 niveles (crítica, alta, media, baja) con colores semánticos, y indicador visual diferenciado para tareas bloqueadas con campo de motivo de bloqueo.',
        context: 'Un equipo de diseño de una agencia gestiona 8 proyectos simultáneos. El director necesita ver el estado global; los diseñadores necesitan ver sus tareas del día.',
        objective: 'App de gestión con vistas coherentes, estados de tarea claros y progreso visible desde el listado.',
        targetUser: 'Dos perfiles: Director de proyecto (vista global, sin ejecutar tareas) y Diseñador/Desarrollador (vista de sus tareas, ejecución diaria).',
        restrictions: [
          'Las vistas lista y Kanban deben mostrar las mismas tareas con los mismos estados.',
          'La prioridad debe ser visible en ambas vistas sin abrir el detalle.',
          'Las tareas bloqueadas deben tener tratamiento visual diferenciado del resto.',
          'El progreso del proyecto en el listado debe calcularse visualmente (barra de progreso, no solo número).',
          'El panel de detalle debe caber en un panel lateral, no en una página completa.',
          'Los miembros del equipo se muestran como avatars apilados con contador si hay más de 3.',
        ],
        deliverables: [
          'Frame del listado de proyectos con datos de 4 proyectos en distintos estados.',
          'Frame de la vista lista de tareas de un proyecto con datos realistas.',
          'Frame de la vista Kanban del mismo proyecto.',
          'Panel lateral de detalle de tarea (abierto sobre la vista lista).',
          'Estado vacío para un proyecto recién creado sin tareas.',
          'Link de Figma + captura PNG.',
        ],
        checklist: [
          'Las tarjetas de proyecto muestran progreso, equipo, fecha y estado de un vistazo.',
          'La vista lista tiene las columnas necesarias para priorizar el trabajo del día.',
          'El Kanban tiene la columna "Bloqueado" con tratamiento visual diferenciado.',
          'El detalle de tarea muestra subtareas, comentarios y log de cambios.',
          'Los 4 niveles de prioridad tienen colores coherentes en ambas vistas.',
          'Los avatars de equipo están apilados y tienen contador de overflow.',
        ],
        commonMistakes: [
          'Vista Kanban y lista con diferentes estados o colores para la misma prioridad.',
          'Barra de progreso sin porcentaje numérico o viceversa.',
          'Panel de detalle que abre una página nueva en lugar de un panel lateral.',
          'Tareas bloqueadas sin campo de motivo o sin diferenciación visual.',
          'Avatars de equipo de tamaño fijo que no se apilan.',
          'Listado de proyectos sin indicadores de salud del proyecto (riesgo, retraso).',
        ],
        difficulty: 5,
        timeLimitMinutes: 95,
        skills: ['saas-ui', 'ux-flows', 'dashboards'],
        rubric: [
          CRIT.ux(true),
          CRIT.consistencia(),
          { name: 'Coherencia entre vistas', description: 'Los estados, prioridades y responsables son idénticos visualmente en lista y Kanban.', isCritical: true },
          CRIT.jerarquia(),
          { name: 'Progreso visible', description: 'El estado y avance de los proyectos es legible desde el listado sin entrar en cada uno.' },
          CRIT.flujo(),
          CRIT.componentes(),
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'Plataforma tipo curso: aprendizaje, progreso y comunidad',
      'Diseñar una plataforma educativa con catálogo, reproductor de lección, progreso del alumno y panel del instructor.',
      'Las plataformas de cursos online tienen dos productos distintos dentro del mismo sistema: la experiencia del alumno (catálogo, reproducción, progreso, certificados) y la experiencia del instructor (creación de contenido, análisis de alumnos, gestión de precios). Diseñar los dos sin que se confundan es el primer reto.\n\nEl reproductor de lección es el corazón del producto para el alumno. Debe combinarse con los recursos de la lección, los apuntes personales y el índice del curso sin tapar el video. La barra de progreso del curso es motivacional: mostrar cuántas lecciones quedan y qué porcentaje está completado aumenta la tasa de finalización.\n\nEl catálogo de cursos requiere filtros por categoría, nivel, duración e instructor, además de búsqueda. Las tarjetas de curso deben comunicar precio, nivel, duración, valoración y progreso si el alumno ya está matriculado, todo en un espacio reducido. La coherencia entre la tarjeta del catálogo y la cabecera de la página de detalle del curso es una trampa común: suelen diseñarse por separado y terminan sin relación.\n\nEl panel del instructor tiene métricas distintas: alumnos totales, tasa de completado, valoración media, ingresos del mes y las lecciones más abandonadas. Esta última métrica es de las más valiosas para mejorar el curso.',
      ['Experiencia alumno vs instructor', 'Reproductor + recursos', 'Progreso motivacional', 'Catálogo con filtros', 'Panel de métricas del instructor', 'Tarjetas de curso'],
      ['Auto Layout', 'Componentes', 'Variantes', 'Prototyping', 'Variables'],
      100,
      {
        title: 'Plataforma tipo curso',
        brief: 'Diseña las pantallas principales de "Upskill", una plataforma de cursos online para profesionales del diseño. La plataforma debe incluir: catálogo de cursos con filtros (categoría, nivel, duración, precio, valoración), tarjetas de curso con imagen, título, instructor, valoración en estrellas, duración, precio y badge de "en progreso" si el alumno ya está matriculado, página de detalle de curso con descripción, currículum expandible por módulos, datos del instructor, valoraciones de alumnos y CTA de compra o de continuar, reproductor de lección con barra lateral de índice del curso (lecciones completadas marcadas, lección actual resaltada), recursos descargables de la lección y campo de notas personales, dashboard del alumno con cursos en progreso, porcentaje de completado, próxima lección recomendada y logros/certificados obtenidos, y panel de instructor con métricas (alumnos totales, tasa de completado, valoración media, ingresos del mes) y lista de lecciones ordenadas por tasa de abandono.',
        context: 'Diseñadores y desarrolladores que invierte en su formación esperan una experiencia tan pulida como las herramientas que usan a diario. Comparan con Domestika, Udemy y Coursera.',
        objective: 'Plataforma educativa con experiencias diferenciadas para alumno e instructor, catálogo filtrable y reproductor con recursos integrados.',
        targetUser: 'Dos perfiles: Alumno (diseñador junior-mid, 22-35 años, aprende en su tiempo libre) e Instructor (diseñador senior, 30-45 años, quiere monetizar su conocimiento).',
        restrictions: [
          'La tarjeta de curso en el catálogo y la cabecera de la página de detalle deben compartir el mismo sistema visual.',
          'El reproductor de lección debe coexistir con el índice lateral sin superposiciones.',
          'El progreso del curso debe ser visible desde el catálogo, el dashboard y dentro del reproductor.',
          'Las lecciones completadas, la actual y las pendientes deben ser visualmente distintas en el índice.',
          'El panel de instructor es completamente diferente al dashboard del alumno: misma app, interfaz distinta.',
          'Las tarjetas de curso tienen badge "en progreso" solo para alumnos matriculados.',
        ],
        deliverables: [
          'Frame del catálogo con filtros activos y resultados (mínimo 6 tarjetas de curso).',
          'Frame de la página de detalle de un curso con currículum expandido.',
          'Frame del reproductor de lección con índice lateral y recursos.',
          'Frame del dashboard del alumno con 3 cursos en distintos estados de progreso.',
          'Frame del panel del instructor con métricas y lista de lecciones.',
          'Estado vacío del dashboard para un alumno recién registrado sin cursos.',
          'Link de Figma + captura PNG.',
        ],
        checklist: [
          'Las tarjetas de catálogo muestran valoración, duración, precio y estado de matrícula.',
          'El reproductor y el índice lateral no se superponen en desktop.',
          'El índice lateral diferencia completada, actual y pendiente visualmente.',
          'El dashboard del alumno tiene progreso visible y próxima acción recomendada.',
          'El panel del instructor tiene métricas de negocio y métricas de contenido (abandono).',
          'El estado vacío del alumno nuevo ofrece CTA al catálogo.',
          'La experiencia del instructor es claramente diferente a la del alumno.',
        ],
        commonMistakes: [
          'Tarjeta de catálogo y cabecera de detalle con sistemas visuales distintos.',
          'Reproductor sin índice lateral o con índice que tapa el video.',
          'Dashboard de alumno que solo muestra cursos sin próxima acción.',
          'Panel de instructor idéntico al dashboard de alumno con datos distintos.',
          'Progreso mostrado solo con número, sin barra visual.',
          'Estado vacío genérico sin CTA específico al flujo del usuario.',
          'Ignorar el estado "curso completado con certificado" en el dashboard.',
        ],
        difficulty: 5,
        timeLimitMinutes: 110,
        skills: ['saas-ui', 'ux-flows', 'dashboards'],
        rubric: [
          CRIT.ux(true),
          CRIT.consistencia(),
          { name: 'Experiencias diferenciadas', description: 'Las interfaces de alumno e instructor son claramente distintas en estructura, métricas y acciones disponibles.', isCritical: true },
          { name: 'Reproductor integrado', description: 'El reproductor, el índice y los recursos coexisten sin superposiciones y la lección actual siempre es identificable.', isCritical: true },
          CRIT.jerarquia(),
          CRIT.flujo(),
          CRIT.responsive(),
          CRIT.profesionalidad(),
          CRIT.devready(),
        ],
      },
    ),
  ],
};
