import { CRIT, type LessonSeed, type PhaseSeed, type ChallengeSeed } from './content-types.js';

function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  estimatedTimeMinutes: number,
  challenge: ChallengeSeed,
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes, challenge };
}

export const phase12: PhaseSeed = {
  code: 'FASE 12',
  title: 'Portfolio y freelancing',
  objective: 'Preparar salida profesional con piezas de portfolio presentables y habilidades para trabajar con clientes reales.',
  unlockedSkills: ['portfolio', 'freelancing'],
  projects: [
    'Case study de app móvil',
    'Case study de SaaS',
    'Landing de portfolio personal',
    'Simulación de cliente freelance',
    'Rediseño profesional completo',
  ],
  lessons: [
    lesson(
      'Case study de app móvil',
      'Documentar y presentar el proceso de diseño de una app móvil como pieza de portfolio.',
      'Un case study no es una galería de pantallas bonitas: es la historia de un problema que resolviste. Los reclutadores y clientes quieren entender tu proceso, no solo el resultado. La estructura básica es: problema → investigación → decisiones clave → resultado medible. Sin esa narrativa, tus pantallas son solo imágenes.\n\nEn una app móvil el caso de uso es concreto y fácil de contar. Elige un flujo crítico (onboarding, checkout, búsqueda) y documenta el antes y el después con anotaciones que expliquen cada decisión. "Cambié este botón a azul porque me gustaba" no es una decisión: "moví la acción principal al pulgar porque el 70% de los usuarios usa el móvil con una mano" sí lo es.\n\nEl antes/después es tu arma más poderosa. Muestra el problema original, el insight que te llevó al cambio y el nuevo diseño. Si tienes métricas, úsalas. Si no, describe el impacto esperado con criterios de usabilidad concretos.\n\nPresenta siempre el caso study en un frame de Figma limpio, con jerarquía tipográfica clara y espacio generoso. El propio diseño del case study es tu primera muestra de criterio visual.',
      ['Estructura de case study', 'Narrativa de proceso', 'Antes/después', 'Anotaciones de decisión', 'Métricas de impacto'],
      ['portfolio', 'mobile-ui', 'prototyping'],
      90,
      {
        title: 'Case study de app móvil',
        brief: 'Documenta el proceso de diseño de un flujo clave de app móvil en un frame de Figma presentable como case study.',
        context: 'Es tu primera pieza de portfolio. Un reclutador pasará 90 segundos leyéndola: debe entender el problema, tu razonamiento y el resultado sin esfuerzo.',
        objective: 'Crear un case study visual en Figma que cuente el proceso completo de un flujo móvil con antes/después y decisiones justificadas.',
        targetUser: 'Reclutador o cliente potencial que evalúa tu perfil.',
        restrictions: [
          'El case study debe tener al menos: portada, definición del problema, antes/después de al menos 2 pantallas, 3 decisiones justificadas y resultado o aprendizaje.',
          'Sin bloques de texto de más de 5 líneas sin apoyo visual.',
          'Máximo 2 fuentes tipográficas en todo el documento.',
          'Todas las anotaciones en español claro y directo.',
        ],
        deliverables: [
          'Frame de Figma con el case study completo (mínimo 6 secciones).',
          'Link compartible + captura de la portada.',
        ],
        checklist: [
          'La portada comunica el proyecto en menos de 5 segundos.',
          'El problema está definido con claridad antes de mostrar soluciones.',
          'Cada decisión de diseño tiene una justificación explícita.',
          'El antes/después es visualmente evidente.',
          'El documento tiene jerarquía tipográfica y ritmo visual.',
          'Ninguna sección parece relleno.',
        ],
        commonMistakes: [
          'Empezar con pantallas sin explicar el problema.',
          'Justificaciones estéticas en lugar de funcionales ("lo puse así porque queda bien").',
          'Case study más largo que valioso: 10 secciones vacías pesan menos que 5 densas.',
          'Tipografía del propio case study descuidada.',
        ],
        difficulty: 4,
        timeLimitMinutes: 90,
        skills: ['portfolio', 'mobile-ui'],
        rubric: [
          CRIT.profesionalidad(),
          { name: 'Narrativa del case study', description: 'El documento cuenta una historia coherente: problema → proceso → solución. Un lector sin contexto lo entiende solo.', isCritical: true },
          CRIT.jerarquia(true),
          CRIT.tipografia(),
          CRIT.ux(),
        ],
      },
    ),

    lesson(
      'Case study de SaaS',
      'Presentar el diseño de un producto SaaS mostrando decisiones de UX complejas y criterio de producto.',
      'Los productos SaaS tienen usuarios expertos, flujos largos y métricas de negocio. Tu case study debe reflejar esa complejidad: no basta con pantallas limpias, necesitas demostrar que entiendes el contexto de uso, las restricciones técnicas y los objetivos del negocio.\n\nElije un problema real de SaaS: un dashboard confuso, un flujo de onboarding con abandono alto, un sistema de permisos poco claro. Define el problema con datos o con evidencia cualitativa (citas de usuarios, tickets de soporte, comparación con la competencia). Esa fase de diagnóstico distingue a un diseñador junior de uno senior.\n\nEn el antes/después de un SaaS, las anotaciones deben incluir el razonamiento de arquitectura de información: por qué reorganizaste la navegación, cómo redujiste los pasos de un flujo, qué jerarquía de acciones priorizaste y por qué. Un cambio de color no es suficiente: necesitas decisiones de estructura.\n\nTermina con impacto: reducción de fricción, mejora de tiempo en tarea, simplificación del flujo. Si es un proyecto personal sin métricas reales, inventa un escenario verosímil con hipótesis justificadas. La honestidad sobre el contexto ("proyecto conceptual") no resta valor si el razonamiento es sólido.',
      ['Arquitectura de información', 'Diagnóstico de UX', 'Flujos complejos', 'Métricas de negocio', 'Hipótesis justificadas'],
      ['portfolio', 'saas-ui', 'dashboards', 'ux-flows'],
      100,
      {
        title: 'Case study de SaaS',
        brief: 'Diseña y documenta la mejora de un flujo o sección clave de un producto SaaS en formato case study de portfolio.',
        context: 'Los clientes y empresas de SaaS buscan diseñadores que entiendan producto, no solo interfaz. Este case study debe demostrar criterio de negocio y de UX a la vez.',
        objective: 'Crear un case study de SaaS con diagnóstico claro, decisiones de arquitectura de información justificadas y antes/después funcional.',
        targetUser: 'Responsable de producto o CTO evaluando contratar a un diseñador.',
        restrictions: [
          'El flujo elegido debe tener al menos 4 pantallas o estados.',
          'El diagnóstico debe incluir al menos 2 problemas identificados con evidencia.',
          'Las decisiones de rediseño deben ir más allá del aspecto visual: estructura, flujo, jerarquía.',
          'El case study debe incluir una sección de "lecciones aprendidas" o "próximos pasos".',
        ],
        deliverables: [
          'Frame de Figma con case study completo.',
          'Flujo rediseñado navegable (prototipo básico).',
          'Link + captura de la sección de antes/después.',
        ],
        checklist: [
          'El diagnóstico identifica problemas concretos, no genéricos.',
          'Las decisiones de diseño están justificadas con criterio de UX o negocio.',
          'El antes/después muestra mejora estructural, no solo visual.',
          'El prototipo permite seguir el flujo rediseñado.',
          'La sección de impacto o aprendizajes es honesta y específica.',
        ],
        commonMistakes: [
          'Rediseñar solo la estética sin tocar la estructura.',
          'Diagnóstico vago ("la interfaz no era intuitiva") sin evidencia.',
          'Omitir las restricciones o el contexto del negocio.',
          'Prototipo con navegación rota o incompleta.',
        ],
        difficulty: 5,
        timeLimitMinutes: 120,
        skills: ['portfolio', 'saas-ui', 'ux-flows'],
        rubric: [
          CRIT.profesionalidad(),
          { name: 'Narrativa del case study', description: 'El documento demuestra pensamiento de producto: problema de negocio, diagnóstico con evidencia, decisiones estructurales y resultado o hipótesis medible.', isCritical: true },
          CRIT.flujo(),
          CRIT.jerarquia(),
          CRIT.ux(true),
        ],
      },
    ),

    lesson(
      'Landing de portfolio personal',
      'Diseñar una landing que venda tu perfil como diseñador de forma clara y profesional.',
      'Tu portfolio online es tu propuesta de valor en formato web. Tiene dos segundos para convencer a alguien de que vale la pena seguir leyendo. Eso significa: quién eres, qué haces y por qué contratarte, en el primer scroll. El resto es evidencia.\n\nLa estructura mínima eficaz es: hero con propuesta clara + 2-3 proyectos destacados + about breve + contacto. No necesitas más. El error más común es construir un portfolio "completo" lleno de proyectos mediocres. Menos piezas, más calidad. Curar es parte del criterio.\n\nEl diseño de la landing en sí es tu prueba de fuego: tipografía sólida, espaciado generoso, jerarquía visual clara. Si tu portfolio parece una plantilla de WordPress de 2014, da igual lo buenos que sean tus case studies. La coherencia entre el contenido y la forma es lo que transmite criterio.\n\nPiensa en la CTA: qué quieres que haga la persona que llega a tu portfolio. Si buscas trabajo en empresa: que descargue tu CV o escriba un email. Si quieres clientes freelance: que rellene un formulario de contacto o reserve una llamada. Diseña el flujo hacia esa acción desde la portada.',
      ['Propuesta de valor', 'Curación de proyectos', 'CTA', 'Jerarquía visual', 'About eficaz'],
      ['portfolio', 'web-ui', 'typography', 'hierarchy'],
      80,
      {
        title: 'Landing de portfolio personal',
        brief: 'Diseña la landing de tu portfolio personal en Figma: propuesta clara, proyectos destacados y contacto.',
        context: 'Esta pieza es a la vez un diseño que entregas y tu carta de presentación. El criterio que apliques aquí es el que juzgarán quienes la vean.',
        objective: 'Landing de portfolio con jerarquía clara, propuesta de valor en el hero y flujo hacia la acción de contacto.',
        targetUser: 'Reclutador, responsable de contratación o cliente potencial freelance.',
        restrictions: [
          'El hero debe comunicar quién eres y qué tipo de trabajo haces sin necesidad de scroll.',
          'Máximo 3 proyectos en la landing (curar, no acumular).',
          'La CTA debe estar visible en el hero y al final de la página.',
          'Sin fondos o tipografías decorativas que compitan con el contenido.',
        ],
        deliverables: [
          'Frame desktop de la landing completa.',
          'Versión mobile de al menos la sección hero.',
          'Link + captura.',
        ],
        checklist: [
          'El hero dice quién eres y qué haces en menos de 10 palabras.',
          'Los 3 proyectos están presentados con título, descripción corta y miniatura.',
          'La CTA es clara y visualmente destacada.',
          'El espaciado y la tipografía son consistentes en toda la página.',
          'La versión mobile mantiene la jerarquía del desktop.',
        ],
        commonMistakes: [
          'Hero genérico ("Hola, soy diseñador UX/UI") sin diferenciación.',
          'Mostrar todos los proyectos sin criterio de selección.',
          'Tipografía del portfolio menos cuidada que la de los proyectos.',
          'Olvidar el mobile hasta el final.',
        ],
        difficulty: 4,
        timeLimitMinutes: 80,
        skills: ['portfolio', 'web-ui'],
        rubric: [
          CRIT.profesionalidad(),
          { name: 'Narrativa del case study', description: 'La landing comunica una propuesta de valor diferenciada y guía al visitante hacia la acción de contacto de forma natural.', isCritical: true },
          CRIT.jerarquia(true),
          CRIT.tipografia(),
          CRIT.responsive(),
          CRIT.alineacion(),
        ],
      },
    ),

    lesson(
      'Simulación de cliente freelance',
      'Gestionar el ciclo completo de un encargo freelance: brief, propuesta, revisiones y entrega.',
      'El diseño freelance no empieza en Figma, empieza en la conversación. Un cliente no sabe lo que quiere con precisión: sabe lo que necesita resolver. Tu trabajo antes de abrir Figma es hacer las preguntas correctas para entender el negocio, el usuario y el resultado esperado. Sin eso, diseñas a ciegas y acumulas revisiones infinitas.\n\nEl brief de cliente es la herramienta clave. Un brief bien hecho incluye: contexto del negocio, objetivo concreto del proyecto, usuarios objetivo, referencias de referencia, restricciones técnicas o de marca, plazos y presupuesto. Si el cliente no te da esto, tú lo preguntas. Si aun así no lo sabes, lo asumes y lo documentas para que el cliente lo valide.\n\nLas revisiones son parte del trabajo, no un problema. La clave es estructurarlas: presenta los diseños con contexto ("decidí esto porque..."), recoge el feedback de forma organizada, distingue entre peticiones de ajuste razonable y cambios de alcance que implican coste adicional. Aprender a decir "eso está fuera del alcance acordado" es tan importante como saber diseñar.\n\nLa entrega final no es mandar un link de Figma. Es preparar los assets organizados, documentar especificaciones básicas y hacer un handoff limpio. El cliente o el desarrollador no tiene por qué saber leer Figma: tu entrega debe ser autoexplicativa.',
      ['Brief de cliente', 'Propuesta freelance', 'Gestión de revisiones', 'Alcance y presupuesto', 'Handoff limpio'],
      ['freelancing', 'dev-mode', 'handoff'],
      110,
      {
        title: 'Simulación de cliente freelance',
        brief: 'Simula un encargo freelance completo: redacta el brief a partir de un enunciado de cliente, diseña la solución, gestiona una ronda de revisiones y prepara la entrega final.',
        context: 'Un cliente ficticio te pide rediseñar la página de inicio de su negocio local. Te da una descripción vaga y tú debes estructurar el proyecto desde cero.',
        objective: 'Completar el ciclo freelance completo: brief documentado, diseño presentado con justificaciones, revisión gestionada y entrega organizada.',
        targetUser: 'Propietario de negocio local sin equipo técnico interno.',
        restrictions: [
          'Debes redactar un brief de cliente de al menos 8 puntos antes de empezar a diseñar.',
          'La propuesta de diseño debe presentarse con anotaciones que justifiquen las decisiones principales.',
          'La ronda de revisión debe incluir al menos 2 cambios recibidos, documentados y resueltos.',
          'La entrega final debe incluir un documento de handoff básico (tipografías, colores, assets exportados).',
        ],
        deliverables: [
          'Documento de brief en Figma o texto (mínimo 8 puntos).',
          'Diseño de la página de inicio con anotaciones.',
          'Registro de la ronda de revisión (qué pidió el cliente, qué cambiaste y por qué).',
          'Frame de handoff con especificaciones básicas.',
          'Link + captura.',
        ],
        checklist: [
          'El brief cubre: negocio, objetivo, usuario, referencias, restricciones y plazo.',
          'Las decisiones de diseño están justificadas en la presentación.',
          'Los cambios de la revisión están documentados con la petición original y la solución aplicada.',
          'El handoff incluye paleta de colores, tipografías y al menos 3 assets exportados.',
          'La entrega es comprensible para alguien que no conoce Figma.',
        ],
        commonMistakes: [
          'Empezar a diseñar sin brief.',
          'Aceptar feedback vago ("no me gusta, hazlo más bonito") sin aclarar qué significa.',
          'Entregar solo el link de Figma sin organizar los assets.',
          'No distinguir entre revisión (incluida) y cambio de alcance (facturable aparte).',
        ],
        difficulty: 4,
        timeLimitMinutes: 110,
        skills: ['freelancing', 'portfolio'],
        rubric: [
          CRIT.profesionalidad(),
          { name: 'Narrativa del case study', description: 'El ciclo completo está documentado con claridad: brief, decisiones, revisiones y entrega. Un cliente real podría seguir el proceso sin ambigüedad.', isCritical: true },
          CRIT.devready(true),
          CRIT.flujo(),
          CRIT.consistencia(),
        ],
      },
    ),

    lesson(
      'Rediseño profesional completo',
      'Ejecutar un rediseño end-to-end presentable como pieza central de portfolio.',
      'El rediseño completo es la pieza más potente de tu portfolio porque demuestra todo a la vez: diagnóstico, proceso, ejecución y presentación. Elige un producto real con problemas reales (puedes elegir una web pública o app conocida), analiza sus puntos débiles con criterio de UX y diseña una solución que los resuelva de forma coherente.\n\nEl diagnóstico es la base. Antes de tocar Figma, documenta los problemas que ves: problemas de jerarquía, flujos rotos, inconsistencias visuales, accesibilidad deficiente, falta de feedback de estado. Ser específico en el diagnóstico es lo que demuestra criterio profesional. "La interfaz es confusa" no vale; "el usuario no sabe cuál es la acción principal en la pantalla de checkout porque hay 4 botones del mismo peso visual" sí.\n\nEl rediseño debe mantener coherencia en todo el flujo: un sistema de color consistente, tipografía con jerarquía definida, componentes reutilizables y espaciado sistemático. Si cambias algo, cámbialo en todas partes. Las inconsistencias en un rediseño son peores que en un diseño nuevo, porque implican que no revisaste tu propio trabajo.\n\nLa presentación del rediseño en portfolio es el paso final y el más subestimado. Un frame de comparación antes/después bien compuesto, con anotaciones claras y una narrativa de proceso, convierte un buen diseño en una pieza de portfolio irresistible. La forma en que cuentas el trabajo vale tanto como el trabajo en sí.',
      ['Diagnóstico de UX', 'Sistema visual consistente', 'Antes/después', 'Presentación de portfolio', 'Criterio profesional'],
      ['portfolio', 'freelancing', 'design-systems', 'components', 'variables'],
      120,
      {
        title: 'Rediseño profesional completo',
        brief: 'Elige un producto real con problemas de UX o visuales evidentes, rediseña un flujo completo de al menos 5 pantallas y preséntalo como pieza central de portfolio.',
        context: 'Esta es tu pieza estrella. Debe demostrar que puedes diagnosticar, decidir, ejecutar y comunicar a nivel profesional. Es la que incluirás en el hero de tu portfolio.',
        objective: 'Rediseño end-to-end con diagnóstico documentado, sistema visual consistente, antes/después anotado y presentación de portfolio lista para publicar.',
        targetUser: 'Reclutador senior o cliente de alto valor evaluando contratarte.',
        restrictions: [
          'El producto elegido debe ser real y accesible públicamente.',
          'El diagnóstico previo debe identificar al menos 5 problemas específicos con criterio.',
          'El rediseño debe cubrir al menos 5 pantallas o estados conectados en prototipo.',
          'El sistema visual debe ser consistente: paleta definida, tipografía con escala, componentes reutilizables.',
          'La presentación de portfolio debe tener portada, diagnóstico, antes/después y resultado en un único frame navegable.',
        ],
        deliverables: [
          'Documento de diagnóstico (mínimo 5 problemas identificados).',
          'Rediseño de 5+ pantallas en Figma con componentes.',
          'Prototipo navegable del flujo rediseñado.',
          'Frame de presentación de portfolio con estructura completa.',
          'Link + captura de la portada del case study.',
        ],
        checklist: [
          'El diagnóstico es específico: cada problema tiene una pantalla y un criterio de UX.',
          'El sistema visual es coherente en todas las pantallas (color, tipo, espacio).',
          'Los componentes se reutilizan correctamente (no duplicados).',
          'El prototipo cubre el flujo completo sin enlaces rotos.',
          'El antes/después es visualmente claro y las mejoras son evidentes.',
          'La presentación de portfolio tiene jerarquía, ritmo y narrativa.',
          'La pieza es publicable sin ajustes adicionales.',
        ],
        commonMistakes: [
          'Rediseñar solo lo visual sin resolver los problemas de UX identificados.',
          'Inconsistencias entre pantallas (espaciados, colores o tipografías distintas).',
          'Prototipo con flujo incompleto o enlaces que no funcionan.',
          'Presentación de portfolio descuidada para un rediseño bien ejecutado.',
          'Elegir un producto demasiado sencillo que no permita demostrar criterio.',
        ],
        difficulty: 5,
        timeLimitMinutes: 120,
        skills: ['portfolio', 'freelancing'],
        rubric: [
          CRIT.profesionalidad(),
          { name: 'Narrativa del case study', description: 'La presentación cuenta el proceso completo con diagnóstico riguroso, decisiones justificadas y resultado evidente. Es publicable sin modificaciones.', isCritical: true },
          CRIT.consistencia(),
          CRIT.componentes(true),
          CRIT.jerarquia(true),
          CRIT.ux(true),
          CRIT.flujo(),
          CRIT.devready(),
        ],
      },
    ),
  ],
};
