import { CRIT, type LessonSeed, type PhaseSeed } from './content-types.js';

// Helper para crear lecciones técnicas con su reto en la Fase 2.
function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  challenge: LessonSeed['challenge'],
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes: 35, challenge };
}

export const phase02: PhaseSeed = {
  code: 'FASE 2',
  title: 'Figma técnico esencial',
  objective: 'Dominar las herramientas base de Figma.',
  unlockedSkills: ['auto-layout', 'constraints', 'components', 'variants'],
  projects: ['Botones reutilizables', 'Cards responsive', 'Navbar responsive', 'Formulario simple', 'Mini landing con Auto Layout'],
  lessons: [
    lesson(
      'Auto Layout de verdad',
      'Entender padding, gap, hug y fill.',
      'Auto Layout es el motor de Figma moderno. Hug = el contenedor se ajusta al contenido; Fill = el hijo ocupa el espacio disponible; Fixed = tamaño fijo. Padding controla el aire interno y gap la separación entre hijos.\n\nSi dominas estos 4 conceptos, tus diseños dejan de romperse al cambiar el texto.',
      ['Padding', 'Gap', 'Hug contents', 'Fill container', 'Fixed size'],
      ['Auto Layout (Shift+A)'],
      {
        title: 'Botones reutilizables',
        brief: 'Crea un botón con Auto Layout que crezca con su texto y soporte icono opcional.',
        context: 'El botón es el primer componente real de cualquier sistema.',
        objective: 'Construir un botón que nunca se rompa al cambiar el label.',
        targetUser: 'Cualquiera que pulse un botón.',
        restrictions: ['Auto Layout obligatorio.', 'El botón debe hacer "hug" al texto.', 'Padding consistente.'],
        deliverables: ['Botón en al menos 2 anchos de texto distintos.', 'Link + captura.'],
        checklist: ['Cambio el texto y no se rompe.', 'Padding y gap consistentes.', 'Capas bien nombradas.'],
        commonMistakes: ['Ancho fijo que corta el texto.', 'Icono mal alineado al baseline.'],
        difficulty: 2,
        timeLimitMinutes: 40,
        skills: ['auto-layout', 'components'],
        rubric: [CRIT.autolayout(true), CRIT.espaciado(), CRIT.capas(), CRIT.consistencia()],
      },
    ),
    lesson(
      'Cards que no se rompen',
      'Combinar Auto Layout anidado y fill.',
      'Una card real es Auto Layout dentro de Auto Layout: contenedor vertical con padding, dentro bloques que hacen fill o hug según convenga. Anidar bien es la clave de los diseños robustos.',
      ['Auto Layout anidado', 'Fill vs hug', 'Resizing'],
      ['Auto Layout', 'Constraints'],
      {
        title: 'Cards responsive',
        brief: 'Diseña una card con imagen, título, texto y botón que se adapte a anchos distintos.',
        context: 'Las cards aparecen en grids responsive por todas partes.',
        objective: 'Card que aguanta cambios de ancho y de contenido.',
        targetUser: 'Usuario navegando un listado.',
        restrictions: ['Auto Layout anidado.', 'La imagen hace fill del ancho.', 'Sin tamaños fijos en el contenido de texto.'],
        deliverables: ['Card en 2 anchos (estrecho y ancho).', 'Link + captura.'],
        checklist: ['Funciona en 2 anchos.', 'El texto no desborda.', 'Padding interno consistente.'],
        commonMistakes: ['Texto con ancho fijo.', 'Imagen deformada.'],
        difficulty: 3,
        timeLimitMinutes: 50,
        skills: ['auto-layout', 'constraints', 'responsive'],
        rubric: [CRIT.autolayout(true), CRIT.responsive(), CRIT.espaciado(), CRIT.capas()],
      },
    ),
    lesson(
      'Navbar que se adapta',
      'Constraints y resizing para barras de navegación.',
      'Una navbar combina elementos que se quedan a la izquierda (logo), al centro o a la derecha (acciones). Con Auto Layout + space between y constraints correctos, la barra se adapta al ancho.',
      ['Space between', 'Constraints', 'Frames anidados'],
      ['Auto Layout', 'Constraints'],
      {
        title: 'Navbar responsive',
        brief: 'Diseña una navbar con logo, enlaces y un botón de acción que se adapte de desktop a tablet.',
        context: 'Encargo universal en webs.',
        objective: 'Barra que reparte el espacio correctamente al redimensionar.',
        targetUser: 'Visitante que navega entre secciones.',
        restrictions: ['Auto Layout con distribución space-between.', 'Funciona en 2 anchos.'],
        deliverables: ['Navbar en desktop y tablet.', 'Link + captura.'],
        checklist: ['El logo queda a la izquierda y las acciones a la derecha.', 'No se rompe al estrechar.'],
        commonMistakes: ['Posiciones absolutas en vez de Auto Layout.', 'Enlaces descentrados.'],
        difficulty: 3,
        timeLimitMinutes: 45,
        skills: ['auto-layout', 'constraints', 'web-ui'],
        rubric: [CRIT.autolayout(true), CRIT.responsive(), CRIT.alineacion(), CRIT.consistencia()],
      },
    ),
    lesson(
      'Formularios bien montados',
      'Inputs, labels y estados con estilos.',
      'Un formulario es una pila de campos consistentes. Define un input con label, placeholder y espacio para mensaje de error, y reutilízalo. Usa estilos de texto y color.',
      ['Inputs', 'Labels', 'Estilos de texto', 'Estilos de color'],
      ['Auto Layout', 'Estilos'],
      {
        title: 'Formulario simple',
        brief: 'Diseña un formulario de contacto (nombre, email, mensaje, botón) consistente.',
        context: 'Base de cualquier producto.',
        objective: 'Campos consistentes y alineados con buena legibilidad.',
        targetUser: 'Usuario que rellena datos.',
        restrictions: ['Todos los campos comparten el mismo patrón.', 'Auto Layout vertical.', 'Estilos de texto y color definidos.'],
        deliverables: ['Formulario completo.', 'Link + captura.'],
        checklist: ['Campos idénticos en spacing.', 'Labels claras.', 'Botón con buen contraste.'],
        commonMistakes: ['Campos con alturas distintas.', 'Placeholder como label.'],
        difficulty: 2,
        timeLimitMinutes: 50,
        skills: ['auto-layout', 'forms', 'typography'],
        rubric: [CRIT.autolayout(), CRIT.consistencia(), CRIT.tipografia(), CRIT.alineacion()],
      },
    ),
    lesson(
      'Todo junto: mini landing',
      'Ensamblar componentes con Auto Layout de página.',
      'Una página entera puede ser un único Auto Layout vertical que apila secciones. Reutiliza los componentes que ya creaste (botón, card, navbar) para construir más rápido y consistente.',
      ['Auto Layout de página', 'Reutilización', 'Secciones'],
      ['Auto Layout', 'Componentes'],
      {
        title: 'Mini landing usando Auto Layout',
        brief: 'Monta una landing corta (navbar + hero + 3 cards + footer) totalmente con Auto Layout.',
        context: 'Demuestra que sabes ensamblar una página robusta.',
        objective: 'Página entera que se reflowa sin romperse.',
        targetUser: 'Visitante de la landing.',
        restrictions: ['Toda la página en Auto Layout.', 'Reutilizar componentes propios.', 'Máximo 2 fuentes.'],
        deliverables: ['Landing completa en frame.', 'Link + captura.'],
        checklist: ['Cambio textos y nada se rompe.', 'Reutilicé componentes.', 'Ritmo vertical consistente.'],
        commonMistakes: ['Mezclar posicionamiento libre con Auto Layout.', 'Duplicar en vez de instanciar.'],
        difficulty: 3,
        timeLimitMinutes: 70,
        skills: ['auto-layout', 'components', 'web-ui', 'responsive'],
        rubric: [CRIT.autolayout(true), CRIT.consistencia(), CRIT.espaciado(), CRIT.capas(), CRIT.profesionalidad()],
      },
    ),
  ],
};
