import { CRIT, type LessonSeed, type PhaseSeed } from './content-types.js';

function lesson(
  title: string,
  objective: string,
  theory: string,
  concepts: string[],
  tools: string[],
  estimatedTimeMinutes: number,
  challenge: LessonSeed['challenge'],
): LessonSeed {
  return { title, objective, theory, concepts, tools, estimatedTimeMinutes, challenge };
}

export const phase07: PhaseSeed = {
  code: 'FASE 7',
  title: 'Variables, tokens y design systems',
  objective: 'Entrar en nivel profesional.',
  unlockedSkills: ['variables', 'tokens', 'design-systems'],
  projects: [
    'Sistema de color con variables',
    'Sistema de spacing',
    'Modo claro/oscuro',
    'Design system pequeño',
    'Documentación para developers',
  ],
  lessons: [
    lesson(
      'Color tokens: la base de todo sistema',
      'Definir una paleta de color estructurada en variables de Figma listas para exportar a CSS.',
      'Un sistema de color profesional no empieza por "qué bonito queda este azul", sino por estructura. Los color tokens tienen dos capas: primitivos (todos los valores de la paleta, p.ej. blue-500: #3B82F6) y semánticos (brand-primary, surface-default, text-muted). Los primitivos son la fuente de verdad; los semánticos referencian primitivos y definen el significado.\n\nEn Figma, las Variables de tipo Color permiten crear exactamente esta jerarquía. Organiza las colecciones: una colección "Primitives" con todos los tonos y otra "Semantic" que las consume. Así, si cambias un primitivo, todo el sistema se actualiza solo.\n\nLa relación con CSS es directa: cada variable de Figma corresponde a una custom property (--color-brand-primary). Cuando el equipo de frontend exporta con el plugin Tokens Studio o Variables to CSS, el archivo resultante es exactamente lo que el developer necesita sin reinterpretación manual.\n\nNombra siempre en kebab-case, sin espacios ni mayúsculas. Un token mal nombrado es un bug en producción.',
      ['Color primitivos', 'Color semánticos', 'Variables de Figma', 'CSS custom properties', 'Colecciones'],
      ['Variables (panel local)', 'Tokens Studio plugin'],
      55,
      {
        title: 'Sistema de color con variables',
        brief: 'Define un sistema de color completo con dos colecciones: Primitives (paleta base) y Semantic (roles de color). El sistema debe ser exportable a CSS sin ambigüedad.',
        context: 'Una startup SaaS necesita reemplazar su colección de estilos de color dispersos por un sistema de tokens estructurado que el equipo de frontend pueda consumir directamente.',
        objective: 'Crear dos colecciones de variables de color en Figma — primitivos y semánticos — correctamente referenciadas entre sí, aplicadas a un componente de ejemplo.',
        targetUser: 'Designer y desarrollador frontend que comparten el mismo sistema.',
        restrictions: [
          'Mínimo 5 colores primitivos con al menos 5 tonos cada uno.',
          'Mínimo 12 tokens semánticos (brand, surface, text, border, feedback).',
          'Los tokens semánticos deben referenciar primitivos, nunca valores hex directos.',
          'Nomenclatura kebab-case estricta.',
          'Un componente de ejemplo (card o botón) aplica únicamente tokens semánticos.',
        ],
        deliverables: [
          'Archivo Figma con las dos colecciones de variables visibles en el panel.',
          'Componente de ejemplo que usa solo tokens semánticos.',
          'Captura del panel de variables con la estructura completa.',
        ],
        checklist: [
          'Las colecciones están separadas: Primitives y Semantic.',
          'Cada token semántico apunta a un primitivo, no a un hex.',
          'Cambio un primitivo y el componente se actualiza solo.',
          'La nomenclatura es consistente y en kebab-case.',
          'El componente no tiene colores locales, solo variables.',
        ],
        commonMistakes: [
          'Poner valores hex directos en los tokens semánticos.',
          'Mezclar primitivos y semánticos en la misma colección.',
          'Nombres ambiguos como "azul-claro" en lugar de "brand-primary-200".',
          'Crear tokens semánticos sin pensar en su significado (copiar la paleta entera).',
        ],
        difficulty: 3,
        timeLimitMinutes: 55,
        skills: ['variables', 'tokens', 'design-systems', 'color'],
        rubric: [
          CRIT.consistencia(),
          CRIT.color(),
          { name: 'Escalabilidad del sistema', description: 'Los tokens semánticos referencian primitivos y el cambio se propaga correctamente a todos los usos.', isCritical: true },
          { name: 'Nomenclatura exportable', description: 'Los nombres siguen kebab-case y se corresponden con nombres de CSS custom properties válidos.', isCritical: false },
          CRIT.capas(),
        ],
      },
    ),
    lesson(
      'Spacing tokens: ritmo y consistencia',
      'Crear un sistema de espaciado basado en una escala matemática y aplicarlo con variables.',
      'El spacing es el aspecto más ignorado y el que más daña la consistencia visual. Sin sistema, cada diseñador elige "a ojo" y el resultado es una lista interminable de valores únicos que el frontend interpreta de forma distinta cada vez.\n\nUn sistema de spacing comienza con una unidad base (8 px es el estándar de la industria) y una escala multiplicativa: 4, 8, 12, 16, 24, 32, 48, 64… Estos valores se convierten en tokens: spacing-1 (4px), spacing-2 (8px), spacing-3 (12px), etc. Algunos equipos añaden una capa semántica encima: spacing-component-padding, spacing-section-gap.\n\nEn CSS, estos tokens se mapean directamente a custom properties y a configuración de Tailwind (spacing scale). Cuando el diseñador y el developer usan el mismo nombre de token, la handoff se reduce a cero discusión.\n\nAplica los tokens en Auto Layout: padding y gap siempre desde variables. Nunca introduzcas valores manuales en producción.',
      ['Escala de espaciado', 'Unidad base (8px)', 'Spacing tokens', 'Spacing semántico', 'Tailwind spacing'],
      ['Variables (tipo Number)', 'Auto Layout'],
      60,
      {
        title: 'Sistema de spacing',
        brief: 'Define una escala de spacing en variables numéricas de Figma y aplícala en un conjunto de componentes para demostrar consistencia total sin valores manuales.',
        context: 'El equipo de frontend usa Tailwind CSS. Necesitan que los valores de espaciado del diseño coincidan exactamente con la escala de Tailwind para eliminar la traducción manual.',
        objective: 'Crear una colección de variables numéricas de spacing basada en múltiplos de 4 u 8, y aplicarla en al menos tres componentes distintos sin ningún valor de spacing manual.',
        targetUser: 'Developer frontend que implementa directamente los tokens del sistema.',
        restrictions: [
          'Escala mínima: 8 valores (desde 4px hasta 64px).',
          'Variables de tipo Number en Figma.',
          'El padding y gap de todos los componentes del ejercicio deben venir de variables.',
          'Ningún valor de spacing introducido manualmente en ningún componente.',
          'Documentar en el mismo frame la escala completa visualmente.',
        ],
        deliverables: [
          'Colección "Spacing" en el panel de variables con la escala completa.',
          'Tres componentes (p.ej. botón, card, lista) con spacing desde variables.',
          'Frame de documentación visual de la escala.',
          'Captura + link.',
        ],
        checklist: [
          'La escala sigue múltiplos de 4 u 8 sin valores arbitrarios.',
          'Todos los paddings y gaps de los componentes usan variables.',
          'No hay ningún valor de spacing introducido manualmente.',
          'El frame de documentación muestra cada token con su nombre y valor.',
        ],
        commonMistakes: [
          'Escala con valores arbitrarios (7px, 13px, 22px).',
          'Variables de spacing que no se usan en los componentes.',
          'Usar estilos en lugar de variables numéricas.',
          'Confundir padding interno con gap entre elementos.',
        ],
        difficulty: 3,
        timeLimitMinutes: 60,
        skills: ['variables', 'tokens', 'design-systems', 'spacing'],
        rubric: [
          CRIT.espaciado(true),
          CRIT.consistencia(),
          { name: 'Escala matemática', description: 'Los valores siguen una progresión lógica basada en múltiplos de 4 u 8, sin valores arbitrarios.', isCritical: true },
          CRIT.autolayout(),
          CRIT.devready(),
        ],
      },
    ),
    lesson(
      'Modo claro y oscuro con variables',
      'Implementar light/dark mode en Figma usando modos de variables sin duplicar ningún componente.',
      'El modo claro/oscuro es hoy un requisito de producto, no un extra. El error clásico es duplicar frames: uno claro y otro oscuro. Con Variables de Figma, esto es innecesario y contraproducente. Un solo componente puede cambiar de modo porque sus tokens semánticos (surface-default, text-primary) resuelven a valores distintos según el modo activo.\n\nEn Figma, los modos se definen dentro de la misma colección. La colección Semantic tiene dos modos: Light y Dark. Cada token semántico tiene un valor por modo. Al cambiar el modo en un frame, todos los componentes dentro se actualizan automáticamente.\n\nEsta arquitectura es exactamente lo que hace CSS con prefers-color-scheme o con una clase .dark en el HTML. El developer no necesita escribir dos versiones del componente; solo cambia el valor de las variables. El diseñador que entiende esto tiene una ventaja enorme en equipos de producto.\n\nAtención a los tokens de feedback (error, success, warning): también deben tener versiones por modo. El rojo de error sobre fondo oscuro no puede ser el mismo hex que sobre fondo claro.',
      ['Modos de variables', 'Light mode', 'Dark mode', 'Tokens semánticos por modo', 'prefers-color-scheme'],
      ['Variables (modos)', 'Frame > modo activo'],
      65,
      {
        title: 'Modo claro/oscuro',
        brief: 'Implementa light y dark mode en una interfaz de tres pantallas usando modos de variables. Los componentes no deben duplicarse: un solo componente, dos modos.',
        context: 'Un producto B2C necesita dark mode en su app. El equipo de desarrollo ya tiene la lógica en CSS; necesitan que el diseño use la misma estructura de tokens para que la implementación sea directa.',
        objective: 'Crear dos modos (Light/Dark) en la colección semántica y aplicarlos a tres pantallas completas sin duplicar ningún componente.',
        targetUser: 'Usuario del producto que activa dark mode desde su sistema operativo.',
        restrictions: [
          'Un solo set de componentes, dos modos: ninguna copia de componente para el modo oscuro.',
          'Todos los colores de texto, fondo y borde deben venir de tokens semánticos con modo.',
          'Incluir tokens de feedback (error, success) con sus variantes de modo.',
          'Al cambiar el modo del frame, toda la pantalla cambia sin edición manual.',
        ],
        deliverables: [
          'Tres pantallas en modo Light.',
          'Las mismas tres pantallas en modo Dark (mismo componente, modo cambiado).',
          'Panel de variables con la colección semántica y sus dos modos visibles.',
          'Captura + link.',
        ],
        checklist: [
          'Cambio el modo del frame y todo el contenido se actualiza solo.',
          'No existe ningún componente "versión dark" duplicado.',
          'Los textos, fondos y bordes usan solo tokens semánticos.',
          'Los colores de feedback tienen variante de modo.',
          'El contraste es adecuado en ambos modos.',
        ],
        commonMistakes: [
          'Duplicar los componentes para el modo oscuro.',
          'Usar colores locales (hex manuales) en algún elemento.',
          'Dark mode con fondo negro puro (#000000) en lugar de un gris oscuro.',
          'No revisar el contraste de texto en el modo oscuro.',
        ],
        difficulty: 4,
        timeLimitMinutes: 65,
        skills: ['variables', 'tokens', 'design-systems', 'color'],
        rubric: [
          { name: 'Implementación de modos', description: 'El cambio de modo se aplica con la función nativa de modos de Figma, sin componentes duplicados.', isCritical: true },
          CRIT.consistencia(),
          CRIT.color(),
          CRIT.accesibilidad(),
          CRIT.devready(),
        ],
      },
    ),
    lesson(
      'Design system pequeño y funcional',
      'Ensamblar un design system mínimo completo: tokens, componentes y variantes conectados.',
      'Un design system no es una biblioteca de componentes bonitos. Es un contrato entre diseño y desarrollo: los mismos nombres, los mismos valores, el mismo comportamiento. Un sistema pequeño bien hecho vale más que un sistema enorme sin coherencia.\n\nLa arquitectura mínima tiene tres capas: (1) Foundations — tokens de color, spacing, tipografía y elevación; (2) Components — botón, input, card, badge, avatar al menos; (3) Patterns — combinaciones de componentes para casos de uso reales (formulario de login, card de producto). Cada componente usa solo tokens de foundations, nunca valores manuales.\n\nLas variantes de Figma permiten modelar los estados de un componente (default, hover, disabled, error) en un solo objeto. Si un botón tiene 4 variantes × 3 tamaños × 2 modos = 24 estados, pero son un único componente con variables de modo y variantes de estado. Este modelo de datos es el que el frontend implementa con props de React o modificadores de BEM.\n\nDocumentar el sistema en el mismo archivo: una página "Foundations" con las escalas, una página "Components" con los componentes y sus variantes, una página "Patterns" con ejemplos de uso. Sin documentación, el sistema muere en dos semanas.',
      ['Foundations', 'Components', 'Patterns', 'Variantes de estado', 'Props de componente'],
      ['Variables', 'Componentes', 'Variantes', 'Auto Layout'],
      75,
      {
        title: 'Design system pequeño',
        brief: 'Construye un design system mínimo pero completo con tres páginas: Foundations (tokens), Components (mínimo 5 componentes con variantes) y Patterns (mínimo 2 patrones de uso real).',
        context: 'Una agencia necesita entregar un design system inicial a un cliente SaaS para que su equipo de desarrollo pueda empezar la implementación. El sistema debe ser autosuficiente: cualquier developer debe poder entender cómo usarlo sin preguntar.',
        objective: 'Crear un design system estructurado en tres páginas, con tokens aplicados en todos los componentes y variantes de estado documentadas.',
        targetUser: 'Developer frontend que implementa el sistema sin haber participado en el diseño.',
        restrictions: [
          'Tres páginas obligatorias: Foundations, Components, Patterns.',
          'Mínimo 5 componentes (botón, input, card, badge y uno libre).',
          'Cada componente con al menos 3 variantes o estados.',
          'Ningún componente con colores o spacing manuales.',
          'Light y dark mode funcionales en todos los componentes.',
        ],
        deliverables: [
          'Archivo Figma con las tres páginas completas.',
          'Panel de variables con colecciones de color y spacing.',
          'Captura de cada página + link al archivo.',
        ],
        checklist: [
          'La página Foundations muestra todas las escalas de tokens con nombres.',
          'Los 5 componentes tienen variantes de estado documentadas.',
          'Ningún valor de color o spacing es manual.',
          'Los patterns demuestran cómo combinar los componentes.',
          'Light y dark mode funcionan en toda la librería.',
        ],
        commonMistakes: [
          'Componentes bonitos pero sin variantes de estado (hover, disabled, error).',
          'Foundations existente pero no conectado a los componentes.',
          'Patterns que no son reutilizables (demasiado específicos).',
          'Mezclar estilos locales con variables en el mismo componente.',
        ],
        difficulty: 5,
        timeLimitMinutes: 75,
        skills: ['variables', 'tokens', 'design-systems', 'components', 'variants'],
        rubric: [
          { name: 'Escalabilidad del sistema', description: 'Tokens, componentes y patterns están conectados. Un cambio en foundations se propaga a todos los componentes.', isCritical: true },
          CRIT.componentes(true),
          CRIT.consistencia(),
          CRIT.devready(true),
          CRIT.profesionalidad(),
        ],
      },
    ),
    lesson(
      'Documentación para developers: handoff profesional',
      'Producir documentación técnica del design system que el equipo de frontend pueda consumir sin reuniones adicionales.',
      'La documentación es la diferencia entre un sistema que se adopta y uno que se ignora. Un developer que recibe un archivo Figma sin contexto va a tomar decisiones propias que divergen del diseño. La documentación evita eso.\n\nDev Mode de Figma es el punto de partida: permite al developer inspeccionar medidas, tokens, estados y exportar assets sin necesidad de acceso de editor. Pero Dev Mode solo muestra lo que el designer construyó bien: si los tokens no están aplicados, el developer verá hex manuales; si las capas no están nombradas, verá "Rectangle 47".\n\nMás allá de Dev Mode, un design system profesional incluye: una página de "Usage" por componente (cuándo usar, cuándo no usar, ejemplos correctos vs incorrectos), un changelog de versiones (v1.0 → v1.1: se añadió variante disabled al input), y export de tokens a JSON mediante Tokens Studio o el plugin Variables to CSS. El JSON de tokens es el puente real entre diseño y código.\n\nEl objetivo final es que el developer pueda implementar cualquier componente del sistema sin una sola pregunta de aclaración. Ese es el estándar de un design system maduro.',
      ['Dev Mode', 'Tokens JSON export', 'Usage guidelines', 'Changelog', 'Tokens Studio'],
      ['Dev Mode (Figma)', 'Tokens Studio plugin', 'Variables to CSS plugin'],
      70,
      {
        title: 'Documentación para developers',
        brief: 'Añade al design system del proyecto anterior una capa de documentación técnica: página de Usage para cada componente, guía de export de tokens a JSON y anotaciones de Dev Mode.',
        context: 'El design system del proyecto anterior se va a entregar al equipo de frontend mañana. El tech lead pide que cualquier developer junior pueda entender e implementar cualquier componente sin reuniones adicionales.',
        objective: 'Documentar el design system de forma que sea autosuficiente para un developer: usage guidelines, anotaciones de estados, export de tokens y guía de versioning.',
        targetUser: 'Developer frontend junior sin experiencia previa con el sistema.',
        restrictions: [
          'Página "Usage" con al menos 3 componentes documentados (correcto vs incorrecto).',
          'Página "Tokens" con la estructura JSON de export explicada.',
          'Todos los componentes nombrados correctamente en capas para Dev Mode.',
          'Al menos un componente con anotaciones de medidas y tokens visibles.',
          'Un changelog mínimo con la versión actual del sistema.',
        ],
        deliverables: [
          'Página "Usage" en el archivo Figma con guidelines de al menos 3 componentes.',
          'Página "Tokens" con el esquema de export o captura del JSON generado.',
          'Captura de Dev Mode con el componente inspeccionado mostrando tokens.',
          'Link + capturas.',
        ],
        checklist: [
          'La página Usage muestra ejemplos de uso correcto e incorrecto.',
          'Las capas de todos los componentes tienen nombres semánticos.',
          'Dev Mode muestra tokens (no hex manuales) al inspeccionar un componente.',
          'Existe un changelog con la versión del sistema.',
          'Un developer podría implementar el sistema sin preguntar nada.',
        ],
        commonMistakes: [
          'Documentación que describe el diseño pero no el uso (el "qué" sin el "cuándo y cómo").',
          'Capas sin nombrar que rompen la inspección en Dev Mode.',
          'Tokens no aplicados que hacen que Dev Mode muestre hex manuales.',
          'No incluir casos de uso incorrecto (solo mostrar lo que se debe hacer).',
        ],
        difficulty: 4,
        timeLimitMinutes: 70,
        skills: ['variables', 'tokens', 'design-systems', 'dev-mode', 'handoff'],
        rubric: [
          CRIT.devready(true),
          { name: 'Calidad de documentación', description: 'Las guidelines de uso permiten a un developer implementar componentes sin aclaraciones adicionales.', isCritical: true },
          CRIT.capas(),
          CRIT.consistencia(),
          CRIT.profesionalidad(),
        ],
      },
    ),
  ],
};
