import { CRIT, type ChallengeSeed, type PhaseSeed } from './content-types.js';

// Rúbrica base de control visual reutilizada en los retos de la Fase 1.
const visualRubric = (): ChallengeSeed['rubric'] => [
  CRIT.jerarquia(true),
  CRIT.alineacion(),
  CRIT.espaciado(true),
  CRIT.tipografia(),
  CRIT.color(),
  CRIT.consistencia(),
];

export const phase01: PhaseSeed = {
  code: 'FASE 1',
  title: 'Control visual básico',
  objective: 'Dejar de colocar elementos "a ojo".',
  unlockedSkills: ['grids', 'spacing', 'alignment', 'hierarchy', 'typography', 'color'],
  projects: [
    'Tarjetas UI simples',
    'Sección hero de una landing',
    'Bloque de precios',
    'Página simple de presentación',
    'Rediseño de una sección mal diseñada',
  ],
  lessons: [
    {
      title: 'Espaciado y jerarquía: el 80% del resultado',
      objective: 'Usar un sistema de spacing y crear jerarquía con intención.',
      theory:
        'La mayoría de los diseños amateurs fallan por lo mismo: espaciado inconsistente y falta de jerarquía. No por falta de "creatividad".\n\n' +
        'Adopta una escala de spacing (4, 8, 12, 16, 24, 32, 48…). Todo —márgenes, paddings, separaciones— sale de ahí. Esto elimina las decisiones "a ojo".\n\n' +
        'La jerarquía se construye con tamaño, peso, color y espacio. Lo importante debe verse importante. Si todo grita, nada se entiende.',
      example: 'Una card: título 16/600, descripción 14/400 atenuada, mucho aire entre bloques.',
      concepts: ['Escala de spacing', 'Jerarquía tipográfica', 'Ritmo visual', 'Contraste de tamaño'],
      tools: ['Frames', 'Grids', 'Estilos de texto', 'Alinear'],
      estimatedTimeMinutes: 30,
      challenge: {
        title: 'Tarjetas UI simples',
        brief: 'Diseña un set de 3 tarjetas (por ejemplo: producto, perfil y estadística) limpias y consistentes.',
        context: 'Las cards son el ladrillo de casi toda interfaz. Si dominas la card, dominas medio UI.',
        objective: 'Demostrar control de spacing, jerarquía y consistencia en componentes pequeños.',
        targetUser: 'Usuarios de una app que escanean tarjetas rápidamente.',
        restrictions: ['Usar un sistema de spacing.', 'Máximo 2 fuentes.', 'Máximo 3 tamaños de texto.', 'Sin efectos decorativos innecesarios.'],
        deliverables: ['3 cards en un frame.', 'Mismo sistema de spacing en las tres.', 'Link de Figma + captura.'],
        checklist: ['Spacing en múltiplos coherentes.', 'Jerarquía clara en cada card.', 'Las 3 cards comparten estilo.'],
        commonMistakes: ['Paddings distintos en cada card.', 'Demasiados tamaños de texto.', 'Sombras y bordes gratuitos.'],
        difficulty: 2,
        timeLimitMinutes: 45,
        skills: ['spacing', 'hierarchy', 'alignment', 'typography'],
        rubric: visualRubric(),
      },
    },
    {
      title: 'Composición de una hero',
      objective: 'Componer una sección de impacto con foco claro.',
      theory:
        'Una hero tiene un trabajo: comunicar la propuesta de valor y dar UN paso siguiente (CTA). Todo lo demás es secundario.\n\n' +
        'Usa una rejilla, deja respirar el contenido y crea un único punto focal. El CTA debe ser el elemento con más contraste.',
      example: 'Headline grande + subtítulo + 1 botón primario. Imagen de apoyo, no protagonista del ruido.',
      concepts: ['Punto focal', 'CTA primario', 'Grids', 'Aire / whitespace'],
      tools: ['Layout grid', 'Auto Layout', 'Estilos de texto'],
      estimatedTimeMinutes: 30,
      challenge: {
        title: 'Sección hero de una landing',
        brief: 'Diseña la hero de una landing para un producto a tu elección con headline, subtítulo y CTA.',
        context: 'Es lo primero que ve un usuario. Tiene que entenderse en 3 segundos.',
        objective: 'Crear un punto focal claro y una jerarquía que lleve al CTA.',
        targetUser: 'Visitante que llega por primera vez a la web.',
        restrictions: ['Un solo CTA primario.', 'Máximo 2 fuentes.', 'Usar una rejilla de columnas.'],
        deliverables: ['Hero en frame desktop (1440).', 'Link + captura.'],
        checklist: ['Hay un único punto focal.', 'El CTA es el elemento de mayor contraste.', 'El contenido respira.'],
        commonMistakes: ['Dos CTAs compitiendo.', 'Headline poco legible sobre imagen.', 'Texto pegado a los bordes.'],
        difficulty: 2,
        timeLimitMinutes: 50,
        skills: ['hierarchy', 'grids', 'color', 'typography'],
        rubric: visualRubric(),
      },
    },
    {
      title: 'Tablas de precios que se entienden',
      objective: 'Comunicar opciones y guiar hacia el plan recomendado.',
      theory:
        'Un bloque de precios es una decisión, no una tabla. Reduce la carga: destaca el plan recomendado, alinea las features y mantén consistencia entre columnas.',
      example: '3 planes, el del medio destacado con un badge "Popular" y borde de color.',
      concepts: ['Comparación visual', 'Destacar opción', 'Consistencia entre columnas'],
      tools: ['Auto Layout', 'Componentes', 'Estilos'],
      estimatedTimeMinutes: 30,
      challenge: {
        title: 'Bloque de precios',
        brief: 'Diseña un bloque de 3 planes de precios con un plan recomendado destacado.',
        context: 'Encargo típico de landing SaaS.',
        objective: 'Guiar la decisión del usuario con jerarquía y consistencia.',
        targetUser: 'Cliente potencial comparando planes.',
        restrictions: ['3 columnas alineadas.', 'Un plan destacado.', 'Sistema de spacing consistente.'],
        deliverables: ['Bloque de precios en frame.', 'Link + captura.'],
        checklist: ['Las 3 columnas están perfectamente alineadas.', 'El plan recomendado destaca.', 'Las features se comparan fácil.'],
        commonMistakes: ['Columnas con alturas descuadradas.', 'Precio poco visible.', 'Sin opción destacada.'],
        difficulty: 2,
        timeLimitMinutes: 50,
        skills: ['alignment', 'hierarchy', 'spacing'],
        rubric: visualRubric(),
      },
    },
    {
      title: 'Una página que se lee sola',
      objective: 'Estructurar una página simple con buen ritmo vertical.',
      theory:
        'El ritmo vertical (la separación entre secciones) es lo que hace que una página se sienta ordenada. Define separaciones constantes entre secciones y dentro de cada sección.',
      example: 'Secciones con 96px entre ellas; dentro, bloques separados 24px.',
      concepts: ['Ritmo vertical', 'Secciones', 'Lectura en F/Z'],
      tools: ['Auto Layout', 'Layout grid'],
      estimatedTimeMinutes: 30,
      challenge: {
        title: 'Página simple de presentación',
        brief: 'Diseña una página de una sola columna (about / producto) con 4-5 secciones bien ritmadas.',
        context: 'Página real de presentación que cualquier negocio necesita.',
        objective: 'Demostrar control del ritmo vertical y la consistencia.',
        targetUser: 'Visitante que lee de arriba a abajo.',
        restrictions: ['Separaciones de sección constantes.', 'Máximo 2 fuentes y 3 tamaños.'],
        deliverables: ['Página completa en frame desktop.', 'Link + captura.'],
        checklist: ['Ritmo vertical constante.', 'Jerarquía clara por sección.', 'Sin descuadres.'],
        commonMistakes: ['Separaciones aleatorias entre secciones.', 'Mezcla de estilos.'],
        difficulty: 2,
        timeLimitMinutes: 60,
        skills: ['spacing', 'hierarchy', 'grids'],
        rubric: visualRubric(),
      },
    },
    {
      title: 'Rediseñar lo feo con criterio',
      objective: 'Aplicar todo lo aprendido para arreglar una sección mal diseñada.',
      theory:
        'Rediseñar es la mejor prueba de criterio. Identifica los problemas (espaciado, jerarquía, color, alineación), justifícalos y resuélvelos sin reinventar el contenido.',
      example: 'Antes: todo del mismo tamaño y pegado. Después: jerarquía + aire + alineación.',
      concepts: ['Diagnóstico visual', 'Antes/después', 'Justificación de cambios'],
      tools: ['Todo lo de la fase'],
      estimatedTimeMinutes: 35,
      challenge: {
        title: 'Rediseño de una sección mal diseñada',
        brief: 'Coge una sección fea (búscala o recréala) y rediséñala aplicando spacing, jerarquía y alineación.',
        context: 'Demuestra que sabes ver y arreglar problemas reales.',
        objective: 'Aplicar criterio visual y justificar las decisiones.',
        targetUser: 'El mismo usuario de la sección original.',
        restrictions: ['Mantener el contenido original.', 'Mostrar antes y después.', 'Listar 3 problemas que arreglaste.'],
        deliverables: ['Antes/después lado a lado.', 'Nota con los 3 problemas resueltos.', 'Link + captura.'],
        checklist: ['Se ve la mejora con claridad.', 'He justificado los cambios.', 'Apliqué el sistema de spacing.'],
        commonMistakes: ['Cambiar el contenido en vez del diseño.', 'No justificar.', 'Mejorar estética sin arreglar jerarquía.'],
        difficulty: 3,
        timeLimitMinutes: 60,
        skills: ['hierarchy', 'spacing', 'alignment', 'color'],
        rubric: [...visualRubric(), CRIT.profesionalidad()],
      },
    },
  ],
};
